### ISSUE TITLE
Crystal Map prevents backtracking to ice world

### ISSUE THREAD

**Issue by ghost** [SuperTux/supertux#1030]
**SuperTux version:**
0.6.0-3-gd75e87666

**System information:**
Linux Mint 19.1 Cinnamon
Cinnamon v4.0.8
kernel: 4.15.0-43-generic

##### Expected behavior
Crystal Mine level should stay blue on world map after completion.

##### Actual behavior
Crystal Mine remains red and you cannot go back to ice world due to this.

##### Steps to reproduce actual behavior
Unlock the forest, then backtrack by boat to Crystal Mine.

**Comment by Wuzzy2** [comment]
The bug is actually much worse than that: It seems the entire progress of the first world is erased after you've completed the first world.
I just returned from forest world, saw that crystal cave was red. Then I just re-played crystal cave again to see what happens.
Then I saw that ALL the levels in the first world were red again.

The forest world levels are unaffected.

**Comment by Grumbel** [comment]
This issue should be fixed b9efc54c0. Could anybody give the current git a try?

**Comment by Rusty-Box** [comment]
Issue was fixed. Closing this.
