### ISSUE TITLE
Add difficulty settings for Milestone 2 (0.4.0)

### ISSUE THREAD

**Issue by Savsish** [SuperTux/supertux#105]
Please add difficulty settings for Milestone 2 (0.4.0) so that all players could enjoy supertux, as some of the levels are really frustrating, e.g. on easy there would be more checkpoints, while on hard there would be more badguys.

**Comment by Danfun64** [comment]
That would require a major revision to every level, including addons. I don't think adding difficulty settings is practical, at least for Milestone 2. Maybe afterwards...

**Comment by Savsish** [comment]
I have some ideas:
Yeti:
Easy: 3 hitpoints
Medium: 5 hitpoints
Hard: 9 hitpoints

**Comment by sydneyjd** [comment]
First of all... we don't have the manpower to implement something like this.
Second: We don't want to introduce so many possible bugs  so close to a stable release, mainly because we have no way to fix them because of the lack of devs.
Third: it would be impractical to introduce this into M2.

-Sydney
