### ISSUE TITLE
Pinch Mode for boss fights

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#1083]
An idea for making boss fights in SuperTux more interesting and more challeniging during the final hits would be adding pinch modes for boss enemies (e.g. yeti, ghost tree and future bosses).

In their pinch mode bosses could get more agressive by either getting faster, using a new attack or having existing attacks get more difficult than before, similar to how it is done with the stalactite attack pattern of the yeti.
The pinch mode could be initiated after a boss only has 40% or less of their total health points left (e.g. A yeti with 5 health points initiates his pinch mode after having only 2 or less health points left).

**Comment by weluvgoatz** [comment]
Sounds cool! Would really but the BOSS in BOSS BATTLES. :)

**Comment by Alzter** [comment]
Good idea, but how would you make this?

**Comment by HybridDog** [comment]
I have a suggestion for the ghost tree, which is in my opinion currently too easy to defeat:

After sucking in a lantern with light, it does not die immediately but proceeds to the second boss stage. It coughes up an empty lantern so that Tux can reuse the same lantern until it is defeated.
In the second stage, the treeboss has the same behaviour as in the first stage except that the willowisps which are in the colour of the lantern previously sucked in now do not move left and right but along a cubic B-Spline curve with support points randomly distributed on a hollow circle around the treeboss. To get to the third stage, one of the two colours which were not yet sucked need to be breathed in and coughed up by the treeboss.
In the third stage, only the willowisps in the remaining colour move left and right; the other two move along cubic B-Splines. When the last remaining colour in a lantern is sucked, the boss is defeated.

The willowisps which move left and right should be easier to evade than the ones moving on the B-Spline curves. Therefore the speed and number of the latter ones needs to be tested and configured.

**Comment by Rusty-Box** [comment]
@HybridDog The ghost tree will be totally remade especially the way of how to defeat it.

**Comment by HybridDog** [comment]
Ok, I also have a suggestion to make the jeti more difficult in pinch mode:
After jumping down, instead of walking to the place where it jumps up, it could jump to the place, i.e. jump down, jump to the other side, then jump up.
With this change, there are less possibilities for Tux to hit it.

**Comment by HybridDog** [comment]
> The ghost tree will be totally remade especially the way of how to defeat it.

When is this going to happen and are there any plans on its behaviour yet?

**Comment by Rusty-Box** [comment]
@HybridDog https://forum.freegamedev.net/viewtopic.php?f=67&t=12590&p=88538#p88538

**Comment by Rusty-Box** [comment]
> 
> 
> Ok, I also have a suggestion to make the jeti more difficult in pinch mode:
> After jumping down, instead of walking to the place where it jumps up, it could jump to the place, i.e. jump down, jump to the other side, then jump up.
> With this change, there are less possibilities for Tux to hit it.
> ![2019-04-21-212055_1920x1080_scrot](https://user-images.githubusercontent.com/3192173/56474557-ce83a600-647b-11e9-8f76-e4ee75735405.jpg)
> It could also jump multiple times if the floor where it usually walks is long.

I really like this idea for the pinch mode of the yeti.

**Comment by NickersonRomero** [comment]
bueno yo creo yeti los salto es a lado de tux

**Comment by HybridDog** [comment]
Here's my current yeti defeating record time:
![fot_2020-06-07-20:13:34_426772228](https://user-images.githubusercontent.com/3192173/83976719-0c4fc200-a8fc-11ea-835f-420e4a427faf.jpg)
It dies so quickly because it does not have invincibility time and Tux can ride it up to the right.
