### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by trymeouteh** [SuperTux/supertux#1132]
Please get the Android app onto F-Droid. This way those who avoid Google and do not have Google Play on their device can still get supertux!

**Comment by tobbi** [comment]
The Android app is not governed by us, unfortunately. 

/cc @pelya Is this something you could do?

**Comment by pelya** [comment]
You can grab .apk file here:
https://sourceforge.net/projects/libsdl-android/files/apk/SuperTux/

**Comment by tobbi** [comment]
See also https://forum.f-droid.org/t/supertux-for-android/6496

**Comment by pelya** [comment]
Eh, I've tried once to submit F-Droid recipe for OpenTTD, gave up after
three attempts, my build scripts expect Git repo with all submodules and
also download some libraries from the network, F-Droid build server did not
like it. Source archive should work well enough though.

**Comment by fdroidiordf** [comment]
Hello, 

I'm the person who opened the forum thread on forum.f-droid.org.
I have tried to compile the SuperTuxAndroid-app myself, but didn't manage it because there are only manuals for compiling for desktop (see https://github.com/pelya/supertux/blob/master/INSTALL.md).

Now I scanned the whole repository (https://github.com/pelya/supertux) for an AndroidManifest.xml and run
`grep -r Android
grep -r android`.
I could find some logging related android code, but no AndroidManifest.xml.
Although I don't have much experience in dealing with Android source code, because of the missing manifest it looks like the repository doesn't include the whole code (AFAIK a manifest is always needed fro an android project) .
Am I right?

**Comment by pelya** [comment]
Android compilation instructions are in separate repo:

https://github.com/pelya/commandergenius/blob/sdl_android/project/jni/application/supertux/readme.txt

**Comment by fdroidiordf** [comment]
Thank you very much! :-)
I will try this if I have time.
Maybe you can add a link to it to the pleya/supertux repo?

**Comment by Semphriss** [comment]
Since this is not of our responsibility, I'll close this issue.

**Comment by Freed-Wu** [comment]
Any progress about releasing it to f-droid? I notice that github release provide apk files. If we can install them from f-droid, it will be great.

Similar issues:

- https://github.com/zly2006/zhihu-plus-plus/issues/612
- https://github.com/algerkong/AlgerMusicPlayer/issues/727
- https://github.com/raoxwup/haka_comic/issues/167
- https://github.com/wszqkzqk/PvZ-Portable/issues/316
- https://github.com/open-ani/animeko/issues/580
- https://github.com/OpenRCT2/OpenRCT2/discussions/26735

**Comment by MatusGuy** [comment]
Hi. Not much progress has been made for F-Droid, sorry for that. It should be ready in the next release, however, no guarantees.
