### ISSUE TITLE
Old levelpacks are marked as new

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1251]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
When I open a custom levelpack and return, the level count is not destroyed.

##### Actual behavior
When I open a custom levelpack on which I have already completed a few levels, and then I return to the main menu, and go back to the list of levelpacks, the levelpack in question is now suddenly marked as “\*NEW\*”.

This bug does ont occur in 0.6.0.

##### Steps to reproduce actual behavior
* Download and install custom levelpack
* Play a few levels
* Return

No matter what you do, the levelpack will be marked as new after you return.

**Comment by weluvgoatz** [comment]
I also experience this issue.

**Comment by busybody42** [comment]
On that topic, it ALSO doesn't let me use most fourm addons, no matter WHAT i do, with some exceptions... also, they would STILL show up on the addons part of the main menu, but not in the contrib levels tab itself... and on that topic...

**Comment by busybody42** [comment]
...It ALSO happened in 0.6.0 when I tried to get the old version of serano's island working... remastered doesn't show up, because it wants to get downloaded again, and instead, there's the original... but it listed the original twice for some reason... and when I download remastered serano's islands, it replaced the old one! 
BUT, when I reopen the game, it's back to "download remastered serano's islands, or just play the old one instead." AGAIN!

**Comment by Narre** [comment]
This issue first appeared in d119a4db (26 Dec 2018), it is in  src/worldmap/worldmap_parser.cpp

**Comment by Ordoviz** [comment]
ad80130ab26cbcde36380c217a541841f892b191 temporarily hides the NEW text.

**Comment by Guih48** [comment]
I found something super!

If you unpack the archives "addons" folder and move them to levels folder the bug is no more exist (yes, if you only unpack some worlds, the bug is only mend at unpacked levels) :)

**Comment by Vankata453** [comment]
The `*NEW*` levelset indicator has long since been removed. Additionally, the progress functionality will be restored in #2349.
