### ISSUE TITLE
Ghosttree graphics are incomplete

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1257]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
The ghost tree in the level "Ghosttree's Challenges" looks decent.

##### Actual behavior
The ghost tree still looks like a sketch and is incomplete.

##### Steps to reproduce actual behavior
1. Play Ghosttree's Challenges in the Forest World

**Comment by Rusty-Box** [comment]
I'm closing this as this is not a "bug" as it is simply just an unfinished/ancient placeholder for what the ghost tree will be in the next big release. (As odd as it might sound in a way this was "intentional" as we technically knew what we were doing here and to a weird degree this is how it is supposed to be. Not ideal, I know and personally I don't quite like it as well but it got through.)

Its redesign is already considered for v0.7 including revamped mechanics along with it.
