### ISSUE TITLE
Tux can’t walk on worldmap path with initial alpha set to 0

### ISSUE THREAD

**Issue by Ordoviz** [SuperTux/supertux#1292]
**SuperTux version:** 0.6.1
**System information:** Arch Linux 5.4.5-arch1-1

I’m trying to implement a secret exit for “Icy Valley” in Icy Island that reveals a secret path on the worldmap. Sadly, the path is not walkable although the end sequence changed its alpha to 1 using the “Worldmap fade in” feature.

#### How to reproduce

[This commit](https://github.com/Ordoviz/supertux/commit/047433a117c1ef2158774240e2131d403872072c#diff-daed78d25619fd9114d5be3a9a69509c) contains the changes that I made. You can download the updated files to test for yourself.

I also made [a video](https://peertube.social/videos/watch/b834b712-7740-4b0c-ab54-22c562d2f32f) demonstrating the issue.

I told the sequence trigger in sector “secretexit” of “Icy Valley” to fade worldmap tilemap “secret_path” in. “secret_path” is a new tilemap I created that contains a visible path where previously a hidden path was. Its alpha is set to 0.

When I now complete “Icy Valley” by taking the secret exit, “secret_path” fades in but it’s not walkable. If I set its alpha manually to 1, “secret_path“ *is* walkable. This is the reason I filed an issue because I thought that “fade in” means to set the alpha to 1 but apparently there’s still a difference between a tilemap that faded in and a tilemap with alpha=1.

**Comment by tobbi** [comment]
Is this something that also happens when you set the alpha to 1 manually using the debug menu?

**Comment by Ordoviz** [comment]
I tried to follow [ScriptingTilemap](https://github.com/SuperTux/supertux/wiki/ScriptingTilemap) but I get errors:

```
> sector.secret_path.set_alpha(1);
Squirrel error: Problem while executing command (the index 'sector' does not exist)

> Sector.secret_path.set_alpha(1);
Squirrel error: Problem while executing command (the index 'secret_path' does not exist)
```

I’m sure that `secret_path` exists.

**Comment by tobbi** [comment]
Try `worldmap.secret_path`

**Comment by Ordoviz** [comment]
Here’s what I found out:
- A tilemap needs to solid and its alpha needs to be 1 in order to walk on that tilemap.
- Manually setting these properties if they were initially false or 0 (respectively) doesn’t make the tilemap walkable.

**Comment by tobbi** [comment]
Can you upload the test tilemap that you used?

**Comment by Ordoviz** [comment]
See my first comment.

**Comment by tobbi** [comment]
The problem is that we do not update m_solid_tilemaps in game_object_manager when the solidity of tilemaps is changed.

**Comment by Narre** [comment]
Is this bug still being considered? I know for a fact this worked fine in 0.5.x and broke sometime before 0.6.0 was released. It kinda broke a massive worldmap I've been working on for the past two years. I use it to make shortcuts to different islands accessible as you reach the islands because the map is huge and traversing it by foot takes forever. It was kinda meant to be a replacement (and apology) for the abomination called Narre Land :D

Speaking of Narre Land, would anyone mind removing it from Add-Ons? The first level is almost impossible anyway since badguys stopped squishing each other in 0.3.4 (and I made it when I was like 10 or something).

Also, does anyone at least know about a workaround for this bug? (opening paths in the worldmap by scripts without placing a 'castle door' type level in the way)
