### ISSUE TITLE
Should we remove powerup stacking?

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#1318]
Currently in SuperTux collecting multiple of the same powerup boosts their powers, like being able to shoot more bullets with the fire and ice flowers or being able to float longer with the air flower. Although is this a good thing?

I think that a problem with having this is that getting the base level powerups doesn't feel like much of an achievement and they're not that powerful, especially the air flower which has such a short float time you barely even notice it.

Another problem with powerup stacking is it makes you more incentivised to restart a level if you get hit with a high level powerup, as it's easier to just restart than collect at least ten powerups all over again, which can disrupt the flow of a level, where as in Milestone 1 if you got hit with a fire-flower it was easier to just continue the level and pick up another.

The last issue with powerup stacking is it's not immediately obvious. I know a new powerup level indicator has been added but still, it's more simple to just have powerups that work from the get go and have their power immediately obvious without needing to collect a lot of them.

**Comment by Rusty-Box** [comment]
I would be in favor of removing the powerup stacking.

**Comment by Ordoviz** [comment]
I’m in favor too. Removing powerup stacking encourages switching between different powerups, making the game more interesting and simpler because we avoid the need to explain the mechanic to the player. The removal of powerup stacking should go in hand with the addition of powerup storage (#473) so that collecting the same powerup multiple times doesn’t waste the powerup. Good default values for bullet count, glide time and stone time are needed.

**Comment by Rusty-Box** [comment]
I suggest if it gets removed that we use "stack nr. 3" as a default so fire/ice flowers can shoot up to 3 projectiles and the air and earth flower abilities last long enough to be useful.

**Comment by busybody42** [comment]
Heck. No.
It's what gives you a purpose to collect more of the same powerup
Mario had no point aside from the useless score going up by 1000
we don't have points at the time of writing, aside from milestone 1... 
This powerup stacking makes supertux extra unique for this purpose compared to other mario clones...
Tl:dr (READ THE FULL THING PLS) Keep powerup stacking...
P.S. maybe we could have the first powerup we get (when we don't have that same powerup when collecting it) use "stack nr. 2" and skip "stack nr. 1" entirely

**Comment by Alzter** [comment]
@busybody42 I think a better solution would just be to have _more_ power-ups in game that give you more fun abilities, so there's more to choose from. I do agree that base level power-ups should be improved but stacking feels overcomplicated and just because it's unique doesn't automatically mean it's good.

**Comment by busybody42** [comment]
...Better reason to try and not to get hit?
I do agree with the base powerup improvement and more powerups, though...

**Comment by Zwatotem** [comment]
I don't think there is a point in this discussion. There is a poor variety of powerups in levels anyway, and if there is they don't change level to level, but stay constant across longer periods. Earth flower is not even used at all (correct me, if that's not the case). So _for now_ I feel like encouragement for more frequent powerup changes doesn't apply.

Overall I feel like this and #1293 should be implemented at once in specifically designed system of economy. I like the idea of powerup slot, but I think it shouldn't be free, like all other micro-activities (Payed: checkpoints, powerup storing, other things, I don't have idea for, but it'll make sense, if we figure out at least some). Additional gain is, that we can easily adjust cost function (can be linear, or exponential) but it won't get confusing - you have cost displayed you buy something, no strange calculations in head on the fly.

Aside from above, what about e.g. starting with level 3 powerup, but then incrementing for every next gained?

_Maybe I could write it in #1293 as well, cause it touches both problems, or even open new issue thread?_

**Comment by Ordoviz** [comment]
> Earth flower is not even used at all

Since 0.6.0 you can collect the earth flower in the forest world (for example in “Through the dark”).

*I wouldn’t have bothered writing this if you didn’t say “correct me, if that's not the case”.*

**Comment by busybody42** [comment]
I guess adding more powerups would be good, but I really think we need some sort of reason to make you not want to get hit and to make you risk getting more of the same powerup...

**Comment by busybody42** [comment]
Umm... crap... this is what slackstone said about my 2 suggestions: 1337 and 1338, if those are correct; they say (SUGGESTION) in the title:
"I'm not sure suggestions in the issue queue are appropriate. Please use this space for reporting actual bugs and issue related communications. Remember Super Tux is a community driven open source game. Folks have limited time. The ST engine is really good, there's scripting and all kinds of examples. Use the force, study it and then make it do what you want."

**Comment by Alasdairbugs** [comment]
Why would you remove a mechanic that literally makes the game more interesting is beyond me. So what if its not obvious to new players? its not too important to them anyway? it doesnt affect their gameplay massively.

Stacked powerups also give you the ability to swap powerups. So if i have a tier 3 air flower, and i collect a fire flower, then sometime later (without taking damage) i pick up another air flower, it becomes tier 4. That makes the game already *so* much more interesting because theres ways to carry your powerups over other levels and swap them in such ways. It doesnt affect new players who dont know it anyway, and it makes it more fun. This is a stupid argument.

Fire flowers that can shoot more bullets by having more stacked is cool. Air flowers that can have more air time with more stacked is cool. It offers a more unique and deeper playstyle. There's only like 3 powerups in this game, and you want to limit it even more? Do you hate fun?

**Comment by Alasdairbugs** [comment]
This should be kept, and if it is, maybe add a statistic at the top left to show how many powerups are stacked, so noobs arent confused i suppose. But it's not like if the graphic didnt exist you can't figure it out yourself. I figured it out pretty easily, by just replaying a level i already beat.. its a cool neat easter egg, and gives the drab powerup system more depth.

**Comment by HybridDog** [comment]
> […] maybe add a statistic at the top left […]

> […] I know a new powerup level indicator has been added  […]

The powerup count is already shown in the latest version:
![fot_2020-05-13-17:53:03_678825651](https://user-images.githubusercontent.com/3192173/81835592-b8db9580-9542-11ea-9cf8-b2f6acf95994.jpg)

**Comment by ScriptForAll** [comment]
I do believe that stacking makes the power-up system more interesting and gives it some depth. However, that only is true to some extent. There's a point when stacking starts to feel rather stale because after a while it's meaningless to grab one more power-up since the player cannot take advantage of the stacked power-up. Gameplay wise, it's the same as having the stack capped at a point.

My suggestion would be introducing tiers to the already existing power-ups. Each tier would be equivalent to a stack of lower tier power-ups (e.g. 5 fireflowers (tier 0) = 1 fireflower (tier 1) ). This also has the advantage of giving the game ways to progress (late game could use higher tier power-ups for instance). Each higher tier should, in my opinion, encompass the lower tiers' abilities so that the core functionality of the power-up doesn't change drastically.

Some ideas for the power-up tiers are:

FIREFLOWER
 -Current Fireflower [Tier 0]
 -Double-hit fireflower [Tier 1 = x5 Tier 0]
 -Ad infinitum hit fireflower [Tier 2 = x15/10 Tier 1 = x75/50 Tier 0]

ICEFLOWER
(I really liked the idea brought upon in #1356 which can go hand in hand with the iceflower power-up tiers.)
  -Current Iceflower [Tier 0]
  -Ice Cutlass [Tier 1]

MINER'S HAT
  In my opinion, this power-up should be something like an item to use on top of a power-up at a level/section (similar to the darkroom gimmick in Super Mario World).
  But if I were to give it an higher tier it would be something really OP (like anime power beam) but it should be either really expensive or have a long time-off.

GLIDING HAT
  - Current [Tier 0]
  - Double Jump [Tier 1 = x7 Tier 0]

**Comment by Ordoviz** [comment]
IMO the tier system makes a lot of sense because you don’t get as excited about collecting your 6th fireflower as you get when you collect your 3rd fireflower. The only problem is that you _very_ rarely collect the same powerup five times. And once you got your Ice Cutlass you would never want to switch to another powerup again (unless there was a powerup storage of course). I also think that a double jump would allow you to skip large sections in existing and upcoming levels (discuss in #1274).

Overall, I like your idea but the devil is in the details.

**Comment by Alasdairbugs** [comment]
@ScriptForAll I think a tier 1 air flower is wildly different to no air flower, you get a 15% speed boost horizontally, you get a higher jump height, backflip height, spring jump height, and a hover ability. So stacking powerups is just a small bonus, and i think that small bonus enhances the gameplay more than just having regular powerups.

The current system we have is fine, it works fluidly, its just a matter of telling the player how it works, maybe by making another decal sign explaining 2 fire flowers = 2 bullets on screen or something.

The gliding hat being changed to have a double jump makes no sense also. Its a hat, not a jetpack. Although jetpack tux would be awesome, no lie there, but, a jetpack would provide more than a double jump. The gliding mechanic makes sense, but i think we need to have a better animation for it because its kind of hard to notice.

Also, your argument to say its meaningless to grab a fire-flower when you have multiple stacked air flowers, doesnt make sense. If you collect a fire flower with a few stacked air flowers, if you grab an air flower again it retains the previous stacked amount you had.

The feature for powerup stacking and swapping is very useful for 100% speedruns, it provides a very unique route, and makes the game have more depth and interest, so i genuinely still have no idea why people still try to oppose this pretty interesting and unique game mechanic that makes it stand out from mario games (being this is a sort of mario clone)

**Comment by HybridDog** [comment]
I hope this is not too off-topic: I would like to have more powerful power-ups which cannot be taken to other levels; currently there is only the Star. A jetpack or hang-glider are interesting examples in my opinion.

**Comment by LizzyBach** [comment]
Yeah, it is a good thing. Don't remove this feature

**Comment by LizzyBach** [comment]
**Plz don't remove power-up stacking.** It opens up many possibilities like if you stack multiple air flowers , then you can make a falling level in which you can fall slowly by holding down the up button to avoid all the obstacles. Before, it was really hard to make a falling level because of the fact that you can only glide for a short period of time. And the power-up stacking works really fine with other power-ups as well. In my opinion, removing power-up stacking will close all the possibilities with them. And the power-up stacking of fire and ice flower works really well. **Non of the power ups become that over-powered after stacking them.** Plz don't remove this feature.

**Comment by LizzyBach** [comment]
I know that more power-ups would be nice but, stacking power-ups is also a nice mechanic.

**Comment by erratic-c-programmer** [comment]
Maybe limit the maximum stacking to, say, 5?

**Comment by Theocrat** [comment]
@Ordoviz pointed out that removing powerup stacking encourages switching between powerups, but I have a better idea. Instead of removing powerup stacking to facilitate switching between powerups, why not instead store the stacking level of each flower's power, and then determine the current abilities based on the number and combination of the flowers stacked up? We can even have combo abilities based on which specific flowers are used.

Consider these rules: 
 - Having at least one air-flower, when you have three or more fire-flowers, makes your fire bullets fly longer as if gravity was pulling them less. The same goes for ice-flowers as well.
  - Having two or more air-flowers makes their power manifest even if you are using fire-flowers or ice-flowers. This goes for the earth-flower's light effect as well.
  - The bonuses obtained from stacking flowers should not improve linearly with flowers stacked, as @ScriptForAll suggested.
  - Also, having both fire and ice flowers allows them to stack. Whichever you have more manifests its effect at any given point in time, but if you have four of each, you get the **omni-gun** bullet, which can destroy anything that either a fire bullet or a freeze bullet could destroy.
  - Having no fire or ice bullet but two of air and earth gives you the **sand-shield** ability, which erects a barrier of sandstorm around you. This barrier is dispelled when you are hit, but protects you from taking damage. It is regenerated at the beginning of every level. This effect requires three of each of the flowers to manifest if you have  fire or ice flower effect as well.

I was thinking of something along these lines.

**Comment by HybridDog** [comment]
Another option is to allow the player to switch powerups with a key. Here are some thoughts:
* The currently available powerups and their counts are stored in an inventory. 
* If Tux is Big Tux or has a powerup, he can switch to a different powerup or unequip it (unequipping means becoming Big Tux)
* If Tux is hit while wearing a powerup, he becomes Big Tux and loses the powerup. Losing the fire flower powerup means that it is removed from the inventory and if the powerup's count is greater than one, a fire flower hat object spawns at the place where Tux was hurt; Tux can then go there and get back the fire flower powerup with a count one smaler than the one before he got hurt. This losing behaviour is analogous for the other powerups.

**Comment by erratic-c-programmer** [comment]
Uh. What if you wanted to freeze a bomb but a tire bike came out and blew up the bomb

that’s really random and bad

**Comment by Guih48** [comment]
Yes, the bomb mechanics could be inproved...

**Anyway the poweup stacking is a good and uniqe system, but it needs to expand to all powerups!**

The fire and ice flower:
_It counts the number of balls that Tux can have (throw) at same time._
This is good engnouth, only the ice powerup needs some correction (freezed enemy mechanics)

The stone (earth) and air (propeller) flower:
_The powerup stacking currently counts nothing (but it's planned to air flower, and it's wery good)_
I think the powerup stacking should count the time of using the ability at one time (Air flower plan :-) [https://github.com/SuperTux/supertux/issues/588](https://github.com/SuperTux/supertux/issues/588) ) 
And at the stone ability the time limit of turning stone (this is a powerup improvement too, because currently you can't turn to stone, but theese ideas are good: [https://github.com/SuperTux/supertux/issues/1399](https://github.com/SuperTux/supertux/issues/1399) ; [https://github.com/SuperTux/supertux/pull/1527](https://github.com/SuperTux/supertux/pull/1527) ; [https://github.com/SuperTux/supertux/pull/1820](https://github.com/SuperTux/supertux/pull/1820) )


And a mechanics improvement: powerup switch (my idea): [https://github.com/SuperTux/supertux/issues/473#issuecomment-962419933](https://github.com/SuperTux/supertux/issues/473#issuecomment-962419933)

**Comment by Vankata453** [comment]
c3c346a0829242983c32997d38b42e5d5174711d removes powerup stacking in favour of the Item Pocket.
