### ISSUE TITLE
(SUGGESTION) Restore the points and score system for future versions

### ISSUE THREAD

**Issue by busybody42** [SuperTux/supertux#1333]
I had an idea... We could bring back the score from milestone 1... every 2000 points, you get another coin at the end of a level... each level tracks their own separate score bar for each attempt, and there's a total score for the entire addon, including story mode... dying will make you lose the points you had gotten before a checkpoint, or all of them if you didn't get one yet, and take away another 1000 as a penalty for dying... if it wasn't at the start of the level, where it doesn't even count...
Each level also has a settable target score, and it saves your high score for that level, (Max score obtained in only 1 single attempt, dying penalties included) so you can try to beat it later...

**Comment by slackstone** [comment]
Hey, there was another recent "suggestion" that I closed because suggestions are not really issues.

Hey Players --- Super Tux has really fun scripting if you like to code stuff, check it out. You can do all sorts of fun once you start looking at examples that are out there.

Remember Kids -- Super Tux is **"Quality Grade Side Scroll Fun"** TM Mr.Tree

**Comment by busybody42** [comment]
umm... the lives and remove powerup stacking things ARE suggestions/arguements, and yet THOSE are open! WHY?
