### ISSUE TITLE
Throw Bomb like Icecube

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1428]
Currently you can throw icecubes in 8 different directions which is very fun and opens a multitude of level design possibilities.  Throwing bombs, however, is a bit strange seen as besides throwing it to the sides and down, the rest of its movement seems to be random.  So if we could throw bombs like icecubes that would be nice.

**Comment by charla-con-galo** [comment]
I concur

**Comment by mbernard2** [comment]
I've looked at this.

Bombs can actually be thrown up, and it works fine when Tux is not moving. We can throw it by holding the Up key while releasing the Action key.

It also works when moving right. You can try it by holding the Up, Right and Action keys at the same time and by releasing Action. Then the bomb is thrown up and right.

However, when walking left and doing the same steps, the bomb simply goes up, not up *and* left. So that's a bug.

***
In contrast with ice cubes, the velocity of a bomb, when released, depends on Tux's velocity. That makes sense because when you're not walking, you usually just want to put the bomb down. And when you're walking, to want the bomb to go in the same direction where you're going. Ice cubes act as if they're "kicked" when released, so they go much further.

But I wonder if we could make Tux throw bombs even further. As of now, they go about three blocks away while walking slowly, but while running, they go further but not enough, and Tux often times ends up being a little too close.

Throwing them far enough is pretty hard, you have to be press three keys at once and release one first and then you can release the two others.

Perhaps we could keep the same behavior when Tux walks slowly (~3 blocks of distance), but give bombs way more velocity when released while running. 

And while we're at it: what if we made the bomb slide for a while (like 0.2~0.3 secs) or bounce slightly when touching the ground, instead of stopping abruptly ?

**Comment by papb** [comment]
> Ice cubes act as if they're "kicked" when released

What if the same is done for bombs?

> And while we're at it: what if we made the bomb slide for a while (like 0.2~0.3 secs) or bounce slightly when touching the ground, instead of stopping abruptly ?

Awesome!

**Comment by mbernard2** [comment]
> What if the same is done for bombs?

We could do that. They wouldn't keep sliding like icecubes, but we could make it so even when Tux has 0 velocity, he pushes the bomb in the direction he's facing.

If the player just wants to release the bomb where he is without throwing it, he could press Down while releasing the Action key.

And also, I wonder if we should do that for all portable objects (blocks, trampolines, etc.), as a matter of consistency. Except of course for a few notable exceptions, like snails or icecubes.

**Comment by Guih48** [comment]
If left or right arrow is pressed, the bomb can thrown, we only have that problem: if we want to throw the bomb, and press left and roghr arrows, we ane moving too :-|
