### ISSUE TITLE
Tux has a lot of unneeded sprites

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#1450]
![image](https://user-images.githubusercontent.com/22513909/87633534-e3cea980-c77e-11ea-87bb-23e8e3beaacf.png)
![image](https://user-images.githubusercontent.com/22513909/87633763-5049a880-c77f-11ea-9d4c-f5eb15eb7104.png)

All the sprites I've highlighted here for Tux either go unused, or could be achieved using sprite rotation or sprite scaling. Can we remove them and replace necessary actions with sprite rotation/scaling?

**Comment by Alzter** [comment]
On top of this I feel Tux's "grow-ladder" animation should be done using sprite stretching as opposed to animation frames, but that may be hard to do.

**Comment by Zwatotem** [comment]
This is held by #1448, at least for vertical swimming sprites.

**Comment by Alzter** [comment]
I've removed Small Tux's running sprites and action in #1110

**Comment by SlackySlackereon** [comment]
There's even unused sprites in Fire Tux's folder! (Not the hat folder). I can't confirm if these are unused or not, but all I can see is the old buttjump graphic in the aforementioned folder (Again, not the hat folder).

**Comment by weluvgoatz** [comment]
PR #1704  helps relieve some of these unneeded sprites.

**Comment by weluvgoatz** [comment]
All of the sprites highlighted that pertain to swimming, have been removed as of the latest commit.

**Comment by GeorgeFromAus** [comment]
Download link?

**Comment by Guih48** [comment]
I don't like raster graphics scalig and rotating

**Comment by Guih48** [comment]
I don't like raster graphics rotating, so some of theese sprites could be useful. 
The climb-grow sprites are not unneeded, because Tux why can't grow on ladder (scaling isn't good because the small tux is black, and big is grey?
 Some sprites could get used for new features (old ground-pound/buttjump sprites to sliding; side-grow to a new wall-running function (like triangle blocks in mario); externded running sprites also could implementes to existing running, or while starred Tux (maybe it could run higher seed while starred?), or a new running action). 
So I think, there aren't any unneeded sprites.
