### ISSUE TITLE
Fix colour menu

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#1451]
**SuperTux version: 0.6.2**
**System information:** *Windows 10*

Currently, the colour menu displays its values as percentages when it's opened.
![image](https://user-images.githubusercontent.com/22513909/86504528-cf90c100-bdfc-11ea-9108-a7eee08bcebf.png)

This is problematic as when you try to edit these values the slider breaks, and the only way you can input colours is through a decimal input.
![image](https://user-images.githubusercontent.com/22513909/86504567-17174d00-bdfd-11ea-8654-222f6f26d3fa.png)

I think it'd be good to revert the colour menu to display the values in decimals when it's opened.

**Comment by HybridDog** [comment]
> This is problematic as when you try to edit these values the slider breaks

How can you edit the values?
When I changed the colour menu, I didn't know that editing them without the sliders in the editor is possible. Is there a key combination for this?

> I think it'd be good to revert the colour menu to display the values in decimals when it's opened.

I have changed the the displayed string so that it shows the colour number in linear RGB colourspace in percent. SuperTux uses sRGB values, so if someone wants to make something half as bright in a real (non-perceived) way, linear number values should be shown.

**Comment by Rusty-Box** [comment]
> How can you edit the values?
When I changed the colour menu, I didn't know that editing them without the sliders in the editor is possible. Is there a key combination for this?

@HybridDog You can by simply pressing backspace to remove the value and typing a new value between 0 and 1. I didn't even know you could use a the sliders. I only new the typing option. :D

**Comment by HybridDog** [comment]
I have tried to fix the problem in #1456. I hope it works correctly and does not break other things.

**Comment by Alasdairbugs** [comment]
i just used the arrow keys and it never broke for me.

however i prefer the old method as you can have a larger variety of colours.
