### ISSUE TITLE
Keyboard: Cannot jump if left+down is held

### ISSUE THREAD

**Issue by Ordoviz** [SuperTux/supertux#1509]
**SuperTux version:** 0.6.0 and master at 52cdc1f74611db4462d644a5b653884ad2d33ca1
**System information:** Arch Linux

##### Expected behavior
Pressing the jump key makes Tux jump.

##### Actual behavior
Jump gets eaten. It does not even show up when you activate the *Show controller* developer option.

##### Steps to reproduce actual behavior
Use a keyboard, hold <kbd>Left</kbd>+<kbd>Down</kbd> and press jump. Using a gamepad works as expected.

**Comment by weluvgoatz** [comment]
I can't reproduce this bug, mainly because I have my controls set as Z+C rather than Alt+Space.  But it seems the keyboard you are using can't use those certain keys all at once.  While it is possible to do, you have to rebind your keys since it appears the spacebar (if you're using that) sn't good with multiple key inputs.  While this isn't a SuperTux problem, rebinding the default controls in this game should be reconsidered in my opinion for such actions.

**Comment by Ordoviz** [comment]
I did use the spacebar and noticed <kbd>Left</kbd>+<kbd>Down</kbd>+<kbd>Space</kbd> does not work in other applications, too. Closing.
