### ISSUE TITLE
Raspberry Pi 3b+ does not maintain constant fps

### ISSUE THREAD

**Issue by singhamitoj** [SuperTux/supertux#1546]
Hello,
I am using a Raspberry Pi 3b+ running Raspbian Buster (Not Raspberry Pi OS, I did not upgrade), and before, I was playing Supertux 0.6.2, and at times, the game would speed up too much, and at other times, like when Tux respawns, it slows down too much. After some time, I started the game again, and it was taking forever to fully start! Is my Raspberry Pi capable enough to play Supertux, or is it the software, whether it is Raspbian or Supertux?

Edit: I was playing Supertux 0.6.1, not 0.6.2.

**Comment by Semphriss** [comment]
Have you tried with older releases? Here's [0.5.1](https://github.com/SuperTux/supertux/releases/tag/v0.5.1), [0.3.5](https://github.com/SuperTux/supertux/releases/tag/v0.3.5) and [0.1.3](https://github.com/SuperTux/supertux/releases/tag/v0.1.3).

SuperTux [has reportedly had many speed issues](https://github.com/SuperTux/supertux/issues/1542) since 0.5.1, and an engine revamp/improvement is planned; you might have more luck with an older version.

**Comment by qwertychouskie** [comment]
@singhamitoj Make sure you have the "Desktop GL" driver enabled in `raspi-config`.  Also I generally recommend running the latest release when possible (usually `sudo apt update && sudo apt upgrade`, though if upstream re-based on a newer Debian release, it's more involved.)

**Comment by singhamitoj** [comment]
Ok, I will try the latest release of Raspberry Pi OS, but I do have the GL driver enabled. It is set to "Fake KMS."

**Comment by singhamitoj** [comment]
Actually, I think it might be full KMS.

**Comment by mrkubax10** [comment]
Any news?

**Comment by singhamitoj** [comment]
I have been inactive for a long time, hence the long wait. I am going to try this on my RPI 4 instead and see if there is any difference.

**Comment by tobbi** [comment]
@singhamitoj Any update?

**Comment by singhamitoj** [comment]
@tobbi I've tested Supertux 0.6.2 on the latest version of RPI OS. I enabled the full GL driver, and I used a 1600x900 monitor. Everything ran smoothly.

**Comment by tobbi** [comment]
Thanks, I'm gonna close this.
