### ISSUE TITLE
Bonus Island 3 secret too big to keep

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#162]
The amount of levels in the Bonus Island 3 secret is too large. 1 is OK but a whole worldmap is just unbelievable. People should be able to play that amount of levels without searching for them. Maybe they should just show the path there.

**Comment by sydneyjd** [comment]
This makes no sense to me.

**Comment by brmbrmcar** [comment]
I mean that you cannot hide a whole worldmap from people.

**Comment by brmbrmcar** [comment]
Why is it closed?

**Comment by sydneyjd** [comment]
I will re-open it, but don't plan on this getting much activity...

**Comment by Hume2** [comment]
These levels are there because they are unlicensed. In fact, this is the only way how to force the people to put licence refferences into their levels. Note that the first level is named "Toilete zone" and the last is named "Sever escape". If you know anyone who has a level among these levels, you can contact him to add a license refference and it could be moved.
The other way is manipulating with the license, but this is commonly rated as a far worse way.

**Comment by brmbrmcar** [comment]
So why isn't it an addon? Because if they do find it...

**Comment by Hume2** [comment]
If we had about ~500 levels, we could be picky.
