### ISSUE TITLE
Does not jump to the right with a held object

### ISSUE THREAD

**Issue by andyun29** [SuperTux/supertux#1651]
**SuperTux version: 0.6.1
**System information: Linux Mint 18.3 Sylvia

##### Expected behavior
Jumping left and right with a held object.
Setup keyboard: jump "w", action "q".

##### Actual behavior
Does not jump to the right with a held object while moving to the right (to left is ok).

##### Steps to reproduce actual behavior
Hold key "q", press key "right" + "w".

**Comment by Semphriss** [comment]
This is likely to be a keyboard problem.

Many keyboards weren't designed to hold multiple keys down at the same time, and as consequence, if you hold "too many" keys (3 or 4 or 5 depending on the keyboards) your computer won't detect any extra inputs. This isn't specific to SuperTux, any application will have the same bug.

Test the same key with another game; does it work?

-----------

As for the fix, for the moment I recommend you rebind your keys so that it won't cause such a "key collision".

**Comment by andyun29** [comment]
Yes, this problem is also present in other game. I want to note that the other keys in this case work fine. Thank you!

**Comment by Semphriss** [comment]
Alright, Ima close this :+1:
