### ISSUE TITLE
Idea: More lenient spike hitboxes

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1725]
As of the latest commit to the swimming revamp branch, the game can now detect if a certain tile type is within a certain range of a certain object.  Once that is merged, we should add in a feature where the hitbox that spikes are able to touch for killable objects is smaller than the static hitbox, making it more lenient (badguys and Tux will have to actually be in the spike somewhat instead of just lightly breezing by it, possibly not even seeming to touch it).
This would also fix that one bug where Tux standing on a rock gets hurt by spikes even though the rock is covering the spike.

I had this idea already but I'm logging it here so it does not get lost.  Any feedback to this idea?

**Comment by Semphriss** [comment]
I support!

Many other games I know have a certain margin of contact and it turns out to play quite nicely. I'd be interested to see what it plays like in SuperTux; I know for instance that sometimes Tux standing exactly 1 tile above spikes (rock overlapping with spikes, tiles next to the spikes, etc.) and it happened that Tux took damage when unexpected. It'd be good to see that gone.
