### ISSUE TITLE
SuperTux needs and alternative to Yoshi !

### ISSUE THREAD

**Issue by RandomPenguin1778** [SuperTux/supertux#1732]
The new version of SuperTux AKA SuperTux 0.7.0 needs an alternative to Yoshi for tux to feed , ride on , swim and even to eat enemies . Please bring an alternative to Yoshi in SuperTux 0.7.0

**Comment by mrkubax10** [comment]
Actually not bad idea.

**Comment by Alzter** [comment]
An equivalent for Yoshi was actually brainstormed for this game a while ago called the [Ice Dragon](http://supertux.lethargik.org/wiki/SuperTux_Meeting_18._August_2007#Ice_Dragon).

It was concepted to be a "rideable enemy", meaning it could attack Tux but also be mountable and used by the player. I'd assume it'd play similar to Yoshi but instead of eating enemies it could shoot ice balls out of its mouth as described in the page I linked above.
![image](https://user-images.githubusercontent.com/22513909/115807777-99c0d580-a42c-11eb-90ed-52d2db17a95e.png)
Here's a concept for what it could look like in game ([from media repo](https://github.com/SuperTux/media/tree/master/images/creatures/snowdragon))

**Comment by Semphriss** [comment]
The issue with that is that it needs to bring something interesting to SuperTux.

SuperTux isn't just a flat copy+paste of Mario games, it has its own look-and-feel that, yes takes great inspiration from Mario, but adds particular twists and pretty much emancipated from its origins. Thinking about it: Tux has a much more realistic approach when it comes to terrains, whereas Mario always has a more cartoony and/or fantasy side.

I would be ready to welcome a mount for Tux, but it needs to be an interesting mechanic and it needs to fit the universe, not just a retexture of Yoshi. For example:
1. What can (and can't) it do? Why would/n't it do that?
2. Considering the answer to above, is it intuitive? Is it coherent with itself? Is it coherent with the rest of the game?
3. Considering 1 and 2, what does it bring to the game? Does it fill a need, beyond simply copying Mario? A need in gameplay? A need in the story?
4. Does the feature affect other current features? Does it require rethinking other features?
5. How much rethinking of the roadmap (upcoming content) does this require? How much space will it take in the story? Will it be enough to justify the complexity of the feature? Won't it be too much?

These questions aren't exhaustive. and even once the thinking part is done, when comes the designing and programming part, more questions will arise.

I can be interested in a Yoshi equivalent in SuperTux, but it needs to be something that _feels_ like SuperTux, not just like Mario, and something that fills some need, more than a mere addition.

**Comment by Laksh61** [comment]
\/
/\
<
>

**Comment by RandomPenguin1778** [comment]
But isn't the Ice Dragon an alternative to Mega Mole ?
