### ISSUE TITLE
Quitting a level while not carrying a lantern properly causes a segfault

### ISSUE THREAD

**Issue by Semphriss** [SuperTux/supertux#1739]
On latest @ master:

1. Open any level with any carriable object.
2. Grab the carriable object, walk to a wall, then release the action key; as to let the object go, but it won't actually go because of the wall.
3. Press escape, restart the level.
4. Repeat steps 2 and 3.
5. The game will crash with a segmentation fault.

When a sector is reset, its destructor is called, except the first time for some reason. Upon calling the sector's destructor, each object will be destroyed. Carriable objects will have an on-destroy listener bound to the player; that is, when they will be destroyed, they'll instruct the player to ungrab said object. However, at this point in the code, the player object will already be destroyed, which the code does not check, therefore accessing dead memory through a dangling pointer and causing a segfault.

**Comment by Narre** [comment]
I have tried to reproduce this bug and I found quite a few ways to do so (I'm not sure if the GhostTree is the same bug, if it's caused by something else, it would probably be better to file it as a separate issue. It seems to me that the game crashes right when the GhostTree should swallow the lantern so I assume it might have the same cause, though the output - which I don't understand - is different).

https://user-images.githubusercontent.com/14074789/117574078-b2dbae80-b0db-11eb-912d-2f8e7841e4cd.mp4
