### ISSUE TITLE
Low frame rates in forest levels. 

### ISSUE THREAD

**Issue by diablo488** [SuperTux/supertux#1851]
**SuperTux version:*SuperTux-v0.6.2-852-g515d0c069-win64*
**System information:** *windows 8.1 | i7 3770 | intel hd 4000(gpu)|1366x768 resolution*
skybox missing/black
in some levels eg: above the artic skies in world one, welcome to Antarctica first level in world 1
![Screenshot (205)](https://user-images.githubusercontent.com/54474885/137454439-878cecea-30b6-4dc5-9ebd-00af94c2992a.png)
![Screenshot (206)](https://user-images.githubusercontent.com/54474885/137454501-b4a2a1f2-6b5e-4c39-902d-4db08c903f17.png)

And low frame rates\fps in level selector menu and in some levels where many layers of background and foreground /transparent exists goes below 40 fps and 30 fps in level selection menu | screenshots below   

![Screenshot (204)](https://user-images.githubusercontent.com/54474885/137454723-47cb5957-6506-4f35-9105-991edebc9980.png)
![Screenshot (207)](https://user-images.githubusercontent.com/54474885/137454856-6fa92f79-6a3a-48e1-96ad-a13c7bacac44.png)

my pc can play halo 4 and crysis , so its not the gpu
I am running it in windowed mode to take screenshots otherwise its always fullscreen

**Comment by diablo488** [comment]
cave levels is also having low frame rate issues

**Comment by diablo488** [comment]
ok, I am currently replaying the entire game if i see any more bugs i will report it,
the fps is very low in the forest levels , i will continue to comment in this issue#1851 as i am playing through the game

**Comment by diablo488** [comment]
do you guys remember the old forest world map in the contrib levels the one with the keys in the top left corner
why dont you guys put that at the end of the game like collect the keys unlock castle defeat nolok get penny back 
its just a idea which popped up in my mind while playing the game i thought all the levels from the old game is going to be in the new forest world map. I am going to play the old version from 2010 again for nostalgia

**Comment by diablo488** [comment]
Idea: if there were a option in the settings to change the renderers it would have been easy to change it for normal peoples who doesn't know how to edit config files and easier for testing purpose too.
Just like the option to change direct x version in gta 5 as an example

**Comment by diablo488** [comment]
Idea: The vsync cannnot be completely disabled by the options menu
Have to go to the config file for that , and a uncap fps/draw redundant frames button would be helpful for those who have high frame rate monitors and help to decrease input lag. And actually vsync increases the input lag and as a platformer game it affects the accuracy of jumps and other stuff

**Comment by Semphriss** [comment]
IIRC, changing renderers was initially meant for devices which did not support a certain renderer at all, which would make the game entirely unusable (see #1667). That's why changing renderers is usually done outside the game. An in-game option wouldn't hurt, although it might not be as easily implemented as regular options.

It picks OpenGL 3.3 by default since that's usually the fastest on the devices that support it well; other options are available when certain versions of OpenGL aren't available. Note that using a weaker rendering engine will turn off certain graphic features (such as refraction, reflection on empty bonus blocks, etc.)

**Comment by Semphriss** [comment]
As for the v-sync, press Ctrl+F2 while in-game to enable developer mode, and toggle the appropriate options. When in developer mode, you can access the debug menu by pressing F2 anytime.

(You can also press F1 for some super-secret options ;p)

**Comment by tobbi** [comment]
Can you guys please see whether the commit above improves anything?

**Comment by HybridDog** [comment]
In the rainy level I get ca. 70 FPS with 5a883afb9 (master) and 6914916a3 (before the changes) with opengl renderer. With opengl20 renderer I get ca. 160 FPS. I have an intel GPU.

**Comment by tobbi** [comment]
I've taken another stab at trying to improve the rendering speed. Can you check the latest nightly?

**Comment by diablo488** [comment]
> I've taken another stab at trying to improve the rendering speed. Can you check the latest nightly?

on SuperTux-v0.6.2-890-g4600d4453-win64 its still 35 fps no change. the last change "b0aff6a" made the level Shocking go from 17 to 35
if you did something after the 890 build idk bc the latest is 890 as of right now as i am commenting

**Comment by tobbi** [comment]
The commit above improves this even further, but I still believe that this is probably the wrong place to fix it. The Opengl33Context is the culprit here, but I don't know enough about this.

**Comment by HybridDog** [comment]
If I understand the compositor code correctly, with Opengl33 it renders almost everything two times per frame, which often halves the frame rate:
http://github.com/SuperTux/supertux/blob/7fbeeda8efd3766e2ae3894e09758818dd853e49/src/video/compositor.cpp#L92
For the reflections the fragment shader needs to access neighbouring pixels from the current image, but a fragment shader cannot read its output image since it's unfinished, so the compositor renders the image one time without reflections and then another time with reflections, where the neighbouring pixels for the reflections are taken from the first rendered image.
With opengl20 there are no reflections, so it probably renders everything only one time per frame.

**Comment by weluvgoatz** [comment]
Is this bug to be considered fixed yet?

**Comment by diablo488** [comment]
i cant download the windows nightly releases  
![Screenshot (41)](https://user-images.githubusercontent.com/54474885/158030701-d84bd77a-ba2c-46bf-8740-5c99a281c001.png)

**Comment by diablo488** [comment]
I bought a gpu.and the fps is always above 150 with draw redundant frames. So i think there is no need for this issue to be open
