### ISSUE TITLE
Fish vanishes when killed by fire flower

### ISSUE THREAD

**Issue by Busybody64** [SuperTux/supertux#1864]
I found this by accident while testing my level, "The first icebergs."

The name is self explanatory. It doesn't even fall offscreen.

I had my audio off, so i'm not sure if it made the "pow" sound like it normally does when it falls offscreen.

**Comment by Busybody64** [comment]
[level1.stl.zip](https://github.com/SuperTux/supertux/files/7462763/level1.stl.zip)

**Comment by Narre** [comment]
I couldn't reproduce it in the attached level (BTW, make all of the water solid, otherwise Tux can only swim in the top tile and then falls to his death), but I have experienced it in one of my own levels (this one: https://gitlab.com/cecflit/narre2/-/blob/master/icecanyon_welcome_to_narres_icecanyon.stl - right at the beginning. note: this level uses a custom tileset, it can be found in the same GitLab repo.)

https://user-images.githubusercontent.com/14074789/139920485-44f1a754-58d7-475c-8089-874c39882ea4.mp4

**Comment by Busybody64** [comment]
If you hit the ! block at the beginning, you'd know you're MEANT to die if you fall into the water.

It's just like that so the fish don't die right away as well.

Anyways, i think the fish just jumped out of the water when i killed it and triggered the bug. Either that, or it was about to fall back in. Probably the former.

**Comment by Semphriss** [comment]
Do you have any output logs for these? (If it did output anything special at all)

**Comment by Busybody64** [comment]
I didn't see anything. I wasn't paying attention, anyways.
I just barely caught it.

**Comment by tobbi** [comment]
I couldn't reproduce the issue with the attached level.

**Comment by tobbi** [comment]
Is this the latest version of SuperTux with all the graphics in place?

**Comment by Busybody64** [comment]
I think it just happened by sheer luck.

**Comment by tobbi** [comment]
> I think it just happened by sheer luck for me.

What do you mean? Did this issue only occur once?

**Comment by Busybody64** [comment]
yep, only once for me.

**Comment by mrkubax10** [comment]
This seems to be very rare, feel free to reopen when this will happen again.
