### ISSUE TITLE
Tux can still swim under the level and die

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1902]
There was a commit a while ago that made it to where if Tux swam at the bottom of the sector, then he would bounce back.  However, this can still be avoided and Tux can still die if the player goes into the bottom-left or bottom-right corners of a swimmable zone at the bottom of a level.
To fix this, I think that these corners should act as a barrier to prevent this issue from happening.  I think if you add barriers underneath the sector this should be fine, but level designers shouldn't have to do this with every swimmable area that reaches the sector bottom.

**Comment by Semphriss** [comment]
I struggle to reproduce this; do you have a video showing the problem?

**Comment by Semphriss** [comment]
The small delay before dying is due to the fact that Tux partly in water is still swimming, and therefore invulnerable to out-of-bounds damage.

The only (viable) fix I see for this would be to make sure and access to tiles at any given out-of-bounds location `[x, y]` should return the same tile (and therefore have the same physical properties) as its closest in-bounds tiles. That would make walls go infinitely far down underneath the tilemaps - but it would also extend tilemaps in other directions, including vertically.

**Comment by Alasdairbugs** [comment]
i think players should just avoid trying to go under levels if they learn it sometimes kills them. usually going to the void kills you so when a player realises they're right in the void on the verge of death, it doesnt take a genius to realise "im about to die if i dont get out of here" so idk

**Comment by weluvgoatz** [comment]
However, the player can just as easily learn that they don't (or at least aren't supposed to) die while swimming and going to the void.  For consistency's sake, I'd say either fix this bug or make the void kill swimming players again.
