### ISSUE TITLE
Left/right scrolling in the editor

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1929]
Currently, scrolling while editing in a sector scrolls the sector up and down.  I think that if the player holds shift or Ctrl while scrolling, the screen should scroll horizontally instead.

**Comment by Narre** [comment]
That wouldn't be very useful. Horizontal scrolling should be possible without having to reach for the keyboard, at that point, you can just use the arrow keys. I'd be in favour of implementing drag&drop (using the middle mouse button), although I am aware that it would not be easy to implement. I really miss the old on-screen scroller. It was useful, it could be hidden to not obstruct whatever's behind it and it allowed the user to scroll through the level without reaching for the keyboard. The undo/redo buttons that are there now are really intrusive and I dare to say that most people are so used to Ctrl+Z so much that they will never use the undo button even when using the mouse.

**Comment by Rami-Slicer** [comment]
Shift would be the better choice for this however allowing people to use the middle mouse button like Narre said or even shift-click-drag would be vastly more friendly for people using a mouse or trackpad.

**Comment by Semphriss** [comment]
> I really miss the old on-screen scroller.

For the info, it still exists, it's just disabled. I think I re-enabled it but only on touchscreen devices, though I'm not entirely sure.

> The undo/redo buttons that are there now are really intrusive and I dare to say that most people are used to Ctrl+Z so much that they will never use the undo button even when using the mouse.

Just a request that we don't completely remove those buttons, again because of mobile. It's harder to do Ctrl+Z on a touchscreen device :smile: 

But indeed, I admit sometimes they are in the way.

**Comment by Narre** [comment]
I think the undo/redo buttons should just be possible to hide, like the old scroller used to be.\
The reason I miss the scroller and would prefer a middle-click scrolling to Ctrl or Shift is simply because when editing a level, I would like to not have to have my left hand on the keyboard at all times

**Comment by Semphriss** [comment]
PR mentioned above got merged, closing this
