### ISSUE TITLE
Particle zone working not as intended

### ISSUE THREAD

**Issue by bruhmoent** [SuperTux/supertux#1933]
**SuperTux version: v0.6.3-beta-1-1-g**
**System information:** *Windows 11*

##### Steps to reproduce actual behavior: Create multiple particles (with different names), then select one of them in the particle zone, observe behaviour

![image](https://user-images.githubusercontent.com/69918580/146061108-f11b1fab-ddee-49e7-b2e4-411d03368d92.png)
Actual behaviour ^
![image](https://user-images.githubusercontent.com/69918580/146061164-b6cb5a7b-e384-43e1-8335-a01a5d54f0b3.png)
Expected behaviour ^

**Comment by Semphriss** [comment]
Can't reproduce.

Here are the steps I tried:
- Open a level
- Go in Objects -> Sector and create two "Custom particles from file"
- Right-click on the first, assign "[/particles]/generic/leaves.stcp" to the File option, and give it the name "a1"
- Right-click on the second, assign "[/particles]/generic/bubbles.stcp" to the File option, and give it the name "a2"
- Go in Objects -> Environment
- Create a Particle zone
- Right-click on the particle zone, give it a Zone Type of Spawn, and a Particle Name of "a2"
- Test the level
- Observed: the particle zone spawns only bubbles, as expected.

If reproducing the steps above still give you the bug, try setting you game in English just in case it's a translation error.

**Comment by Semphriss** [comment]
To keep it in the records: When creating a "Custom particle" object that is **not** from file, the object has the "Cover screen" option on by default, which ignores particle zones and spawn particles anywhere on the screen instead.

This option is on by default so that someone who adds a custom particle object can have immediate feedback and see the particles.
