### ISSUE TITLE
Undo causes level editor to go back to tilemap 0

### ISSUE THREAD

**Issue by Vankata453** [SuperTux/supertux#1954]
**SuperTux version:** 0.6.3 - Beta 1
**System information:** Windows 10

##### Expected behavior
When the undo feature is used in the level editor and the selected tilemap is not 0, there shouldn't be any switching between tilemaps.
##### Actual behavior
When the undo feature is used in the level editor and the selected tilemap is not 0, the editor automatically switches to tilemap 0.
##### Steps to reproduce actual behavior
Open a worldmap or a level in the level editor, choose a tilemap, different than 0, place a tile or an object and undo.

**Comment by Semphriss** [comment]
This is much more difficult to fix because the current undo/redo mechanism works by saving the entire level to the memory on each click and to restore the level from scratch. Unless all tilemaps have a unique identifier that would persist across saves, fixing this bug would probably require a refactor of the UndoManager, which has been in my plans for a while now but which might have to wait until after 0.6.3.

**Comment by Rami-Slicer** [comment]
Darn... Though giving all objects a UID would be a good idea, names aren't guaranteed to be assigned to only one object....

**Comment by Semphriss** [comment]
UIDs do exist - but the same object in different loads will have different UIDs. The current purpose of UIDs is to identify a single object during runtime, to check if it still exists or not. I don't think it would be feasible to automatically detect which object in a load corresponds to which other one in another, considering there could be any degree of difference between both and because two different objects could have the exact same properties, and would therefore be indistinguishable.

**Comment by Vankata453** [comment]
I think it would be really beneficial to have the UndoManager remember just the actions, that have happened to certain objects or tilemaps and then when undo or redo is used, just repeat the saved action. It may be hard to do, though. Maybe you mean this by a "refactor of the UndoManager"?

**Comment by Rami-Slicer** [comment]
I think it would be a good idea anyways to give objects a secondary UID that stays the same always.

**Comment by mrkubax10** [comment]
It is not possible as entire level gets reloaded. I think that fixing this issue is impossible with undo/redo system that we have now
