### ISSUE TITLE
Object sprite changes don't update unless editor is reloaded

### ISSUE THREAD

**Issue by Alasdairbugs** [SuperTux/supertux#1961]
v0.6.3-beta.1.2-gdb0689f97
win 10

changing an object to a different sprite wont change it unless you reload the level editor, by exiting and re-entering it, or going to another stage and coming back, this gets quite annoying and discourages use of decals.

**Comment by Semphriss** [comment]
Tested on latest nightly, changing a decal's sprite updates as soon as the options menu is closed:

https://user-images.githubusercontent.com/66701383/146293742-6f40b158-870b-4aba-b609-f2524deef5f0.mp4

Does it happen with a decal, or with another object?

**Comment by Narre** [comment]
I have come across this too. The sprite of ***some*** objects updates correctly, but that certainly isn't always the case.\
&nbsp;&nbsp;&nbsp;&nbsp;The decal, for example, will update its *appearance* but **not** its *hitbox*, which is really annoying when using a small image (e.g. 32×32), because the decal retains the hitbox of the massive billboard, getting in the way when working with other objects in the vicinity.\
&nbsp;&nbsp;&nbsp;&nbsp;An example of an object that doesn't update its sprite at all is the candle. I often use invisible candles for lighting effects in darker levels, so this was easy to notice. When changing the candle's sprite, it is saved correctly, but the original candle still shows up as candle.sprite. All of its copies (made using the clone tool) get updated properly, but the original will stay visible until a reload.

https://user-images.githubusercontent.com/14074789/146364391-518d5f1b-9988-4595-af39-4c26054eb343.mp4

BTW a bit off-topic, but objects using invisible.sprite should have an editor image, they are so frustrating to work with!

**Comment by Alasdairbugs** [comment]
Yep I guess its some objects. i think the torch is also one.

Also - the first video, if you change a decal. the hitbox for the old decal is still present but the sprite is changed. thats very frustrating when trying to layer objects near each other and you try to move an object but you start moving the decal because it overlaps.

**Comment by Vankata453** [comment]
I have come across this too. Trying to place a level in a worldmap and changing its sprite won't update it, until the worldmap is reloaded in the editor, for example.

**Comment by Rami-Slicer** [comment]
Can confirm as well especially in the worldmap editor with the level dots.

**Comment by Semphriss** [comment]
Does anybody have a list of objects where this happens? I'll take care of this tonight.

**Comment by Vankata453** [comment]
I tested in worldmaps and it only happens with level dots. Haven't still tested with levels.

**Comment by Narre** [comment]
I'm testing it, will report soon.

**Comment by Narre** [comment]
**DON'T UPDATE AT ALL**
`snowball`
`smartball`
`snowman`
`bouncingsnowball`
`captainsnowball`
`flyingsnowball`
`kamikazesnowball`
`mrbomb`
`goldbomb`
`haywire`
`short_fuse`
`mriceblock`
`smartblock`
`spiky`
`sspiky`
`jumpy`
`livefire`
`livefire_asleep`
`livefire_dormant`
`crystallo`
`scrystallo`
`rcrystallo`
`stalactite`
`willowisp`
`flame`
`ghostflame`
`iceflame`
`poisonivy`
`walkingleaf`
`leafshot` (plus the editor seems to think that the default sprite for leafshot is kamikazesnowball.sprite, even though it renders leafshot.sprite)
`snail`
`mrtree`
`stumpy`
`owl`
`zeekling`
`igel`
`mole`
`fish`
`skullyhop`
`spidermite`
`walking_candle`
`toad`
`kugelblitz`
`plant`
`totem`
`angrystone`
`darttrap`
`dispenser` (funnily, it switches between the default sprites for dropper, cannon and rocket launcher even if they are not used and a user-defined sprite is in use instead)
`ghoul`
`yeti`
`ghosttree`
`yeti_stalactite`
`skydive`
`dart`
`candle`
`lantern`
`magicblock`
`level` (worldmap)

**APPEARANCE UPDATES BUT HITBOX DOESN'T**
`icecrusher`
`ispy`
`bonusblock`
`infoblock`
`invisible_block`
`brick`
`heavycoin`
`coin`
`decal`
`powerup`
`platform`
`circleplatform`
`hurting_platform`
`fallblock`
`scriptedobject`
`firefly`
`rock`
`rustytrampoline`
`bumper`
`trampoline`
`unstable_tile`
`weak_block`
`pushbutton`
`switch`
`torch`
`skull_tile`
`special-tile` (worldmap)
`sprite-change` (worldmap)
`teleporter` (worldmap)
`worldmap-spawnpoint` (worldmap; why on Earth is the sprite of that even settable???)
`decal` (worldmap)

**SPRITE CANNOT BE CHANGED FROM EDITOR (WHY???)**
`rublight`
`door`
`spotlight`

**Comment by Semphriss** [comment]
Thanks for the list :+1: I'll start doing that

**Comment by Narre** [comment]
I had a quick look (but I didn't test everything thoroughly). This is what noticed:

- The editor now renders Ice Flames as regular flames by default, even though the game doesn't.
- Same for leafshot - the editor renders them as kamikazesnowballs, the game doesn't.
- Decal still doesn't update its hitbox after a sprite change

![image](https://user-images.githubusercontent.com/14074789/146506436-cdd10270-5955-4cc6-92d7-b02e0ebb6b61.png)
I don't know exactly what you meant by this, but flames, iceflames and ghostflames are not just retextures, they have different behaviours to fire/ice flowers.

- So the sprite of ghost flames should still be settable. The user might have their own sprite for an addon and may not want their flames to be killable with the iceflower(flame) or fireflower(iceflame).
