### ISSUE TITLE
Installing SuperTux From Source on Linux Does Not Work

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#214]
Running 
``# make install`` 
and then 
``# supertux2``  
gives
`` supertux2: error while loading shared libraries: libsquirrel.so: cannot open shared object file: No such file or directory``

**Comment by tobbi** [comment]
I believe this has something to do with the out-o-tree builds. I will assign maths22 to this, because hopefully he can shed some light on this.

**Comment by tobbi** [comment]
@maths22 Ideas?

**Comment by maths22** [comment]
I will take a look shortly. (I think we just need to to set it to install libsquirrel)

**Comment by maths22** [comment]
As it turns out, that is not the issue.  The issue is that "make install" installs to /usr/local/lib, which is not always on the user's path (it is for Ubuntu, but not Fedora, for example).  This is the correct behaviour, but it should be documented in INSTALL.  To fix this issue, see http://unix.stackexchange.com/questions/67781/use-shared-libraries-in-usr-local-lib

When packages are created, the libraries are put in the correct directories, so this is only an issue for "make install," not packaged builds.

**Comment by Karkus476** [comment]
@maths22 thanks, I've resolved this issue. Maybe #219 will make this less complex
