### ISSUE TITLE
Collision rects occurring on main menu screen after exiting level to main menu screen with collision rects on

### ISSUE THREAD

**Issue by CeIestiaI** [SuperTux/supertux#2154]
moderate-heavy lag occurs. how to reproduce it: exit a random level to main menu with collision rects turned on after exiting level. the main menu level will start playing (obviously) but the collision rects will still be there.

**Comment by Semphriss** [comment]
Please:
- Keep titles short and put the details in the description; I have a hard time understanding the title.
- Follow the format given by the template. Include the reproduction steps, the expected behavior and the actual behavior in three separate categories, to help maintainers read and understand your issue easily.

Additionally, from what I understood, this seems to me like this is the expected behavior. The level playing in the background of the main menu is a full sector, and it renders the collision rects as any sector would.
