### ISSUE TITLE
Trampolines and rocks placed on stacked icecrushers causes bouncing and jittering after falling

### ISSUE THREAD

**Issue by CeIestiaI** [SuperTux/supertux#2184]
SuperTux version:| 0.6.3

Expected behavior:| The objects should teleport off to the side and the icecrushers shouldn't bounce on the objects and the objects shouldn't bounce on the icecrushers. The angrystones should move away instead of being inside of each other and jittering or bouncing. The icecrushers should also not be crushed by the objects because the icecrushers are bigger and weigh more.

Actual behavior:| When the bricks are broken, everything falls to the ground and the icecrushers, angrystones, and the objects all start bouncing and jittering on each other. If Tux goes under where the trampolines and rocks are (below the icecrushers), then picks up objects, tux will be crushed and killed by the icecrushers or the objects. The angrystones are pushed through the icecrushers and the objects. Also, when tux goes under and stands there, tux is bouncing and jittering along with partially clipping into the ground.

Steps to reproduce actual behavior:| Recreate the whole thing in the video below, and use ghost mode to go below the objects and go up, it will cause clipping. Or, break all three of the bricks and everything will come falling down. Then, bouncing and other stuff will occur.

Additional debugging information:|
https://user-images.githubusercontent.com/83178674/159185717-e9452ac0-7f71-40ff-9a68-582851e27c96.mp4

**Comment by CeIestiaI** [comment]
unsure why this happens.

**Comment by Semphriss** [comment]
Seems like expected behavior to me - the engine is not designed to take in such complex arrangements. Messy setups are to be expected to produce messy results. Besides, I don't believe the expected behavior is more expectable than the current behavior.

Given that this setup is not expected to happen for a regular user (with a reasonable expectation to have a clear, simple, well-defined and consistent result), I propose to close this. If you have a real use case which requires this exact setup and need it to work a specific way, please narrow it down to clear, individual issues.
