### ISSUE TITLE
Powerup stacks are not reset when the level is reset

### ISSUE THREAD

**Issue by Semphriss** [SuperTux/supertux#2295]
**SuperTux version:** Latest @ master (`v0.6.3-583-g04856232f`)

Entering a level with a flower stack, increasing that stack during the level, then resetting the level does not also reset the powerup stack to what is was when the level was initially started.

- Enter any level with a certain powerup stack.
- While playing, increase that stack by collecting flowers of the same type.
- While still having the (increased) stack, pause the game, and select "Restart level".
- Notice the stack is not reset to what is was at the first step.

**Comment by Brockengespenst** [comment]
Looks like most of these issues have already been fixed since the issue was opened.

The only issue I see right now happens when:
* Start a level with a certain powerup stack
* Pause the game, select "restart level"
* Only on the first time doing this in the level, the current powerup is increased by one

This seems to happen because the amount of powerups is restored, but also set_bonus is called on the player which increases the amount by one again.
