### ISSUE TITLE
Making Tux air or earth on death displays hat

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#234]
It doesn't happen for ice or fire.

**Comment by brmbrmcar** [comment]
![screenshot from 2015-11-21 15 27 56](https://cloud.githubusercontent.com/assets/14400196/11319143/8482e5e6-9064-11e5-9e9d-615aed3f2ed8.png)

**Comment by brmbrmcar** [comment]
I told it to go to earth, an issue itself.

**Comment by LMH0013** [comment]
I can't reproduce in the most recent build of the code.  Falling off the screen produces the same behavior for me (all hats fall off to the side).  I assume you are seeing the hat stick with Tux throughout the death animation.  This reminds me of an early-implementation bug with the new powerups.  Can you provide more information about what version of SuperTux you are experiencing this on?

**Comment by brmbrmcar** [comment]
0.3.5/0.4.0-GIT.

**Comment by LMH0013** [comment]
Well I have fixed this before, so if I can recreate the issue I may be able to fix it again. I am assuming it is as I described and happens all the time. It might help if anyone else is experiencing the same thing.
		
        
		
		 ---- On Fri, 27 Nov 2015 23:29:17 -1000  notifications@github.com  wrote ----0.3.5/0.4.0-GIT.

**Comment by brmbrmcar** [comment]
When did you fix it? My build was updated inJuly.

**Comment by LMH0013** [comment]
It should have been well before July.  However, you should probably update to the most recent code nonetheless.  If you cannot build from the source code yourself, I believe there is now a daily build option available.  Try obtaining a newer version and see if it still happens.

---- On Fri, 04 Dec 2015 06:06:44 -1000 brmbrmcar &lt;notifications@github.com&gt; wrote ---- 

When did you fix it? My build was updated inJuly.

**Comment by brmbrmcar** [comment]
The nightly builds do not work.

**Comment by brmbrmcar** [comment]
I can confirm the bug is still there.

**Comment by LMH0013** [comment]
Did you get the nightly builds to work then?  I've checked on all of my devices and still have not been able to reproduce your error.  Perhaps if you gave some more information such as OS or identify the which specific GIT commit your build was based on (or at least where exactly you obtained the build).  I am mostly confident that the bug is no longer in the most recent code, but I have been wrong before.  Regardless, unless it is reproduced by others there is not much that can be done.

**Comment by brmbrmcar** [comment]
I m running Wine on Ubuntu 14.04. gcecef01 build.

**Comment by LMH0013** [comment]
Well that's odd, I cannot seem to find that commit.  Any reason you are running it through Wine instead of natively on Ubuntu?  My guess is that you have some weird side-branch version of SuperTux with some outdated code.  You should be able to obtain a more recent build here:

http://download.supertuxproject.org/download/

I'm not running Ubuntu, so I cannot check those builds; however, I do know that the Windows build works, so if you cannot get the Ubuntu version to run directly on your system, you should still be able to play in Wine.

**Comment by brmbrmcar** [comment]
I cannot get the native versions to work. My new build is about 3 days old.

**Comment by brmbrmcar** [comment]
This isn't  fixed. It'll probably be fine for now, but leaving this unfixed could lead to serious bugs when more things are implemented. Fix for Post-0.4.0 is recommended.

**Comment by Karkus476** [comment]
@brmbrmcar I doubt this.
