### ISSUE TITLE
Game shut down when changing screen resolution, and won't start again.

### ISSUE THREAD

**Issue by BlueOceanBlueSky** [SuperTux/supertux#2381]
SuperTux version: 0.6.3
System information: Steam Deck, docked and connected to another monitor.

I downloaded this game through the Discover store and played a few hours.  Recently I tried changing the screen resolution, and it caused the game to shut down.  The game won't start up no matter where I try to start it, including the Discover store, in the games section of my OS, and the desktop shortcut in the files.  I even tried uninstalling and reinstalling through the Discover store, and it didn't work.  How do I get the game running again?

Also, is there a way to back up the save files?

**Comment by Semphriss** [comment]
You can reset your settings by going to `~/.local/share/supertux2/` and either deleting the `config` file completely (which will reset your settings, but not your progress), or by opening it and editing the lines containing "window_width" and "window_height" to any value, in pixels.

If you'd like to help us, please provide us with crash logs, including a core dump or the CLI output. The latter may require you to launch the game from a terminal, if that is possible.

Steam automatically backups and syncs all game data automatically, unless you disabled the option in the Steam settings. The game does not provide any option to disable cloud syncing, since the operation is done solely by Steam.

**Comment by tobbi** [comment]
Closing for lack of information.
