### ISSUE TITLE
Door wont open if offscreen

### ISSUE THREAD

**Issue by MatusGuy** [SuperTux/supertux#2759]
Apparently this worked in the 0.6.3 but stopped working in the current nightlies.

How to reproduce: Go to a door and change the camera position using a script. Try to open the door. It fades out but then does nothing.

**Comment by Vankata453** [comment]
I believe this might have been caused by 2db5fbcf9d4f2023096a42085a46b8f6fa750191. Since the door is off-screen, its sprite is not being drawn. The sprite needs to be drawn to update. The door requires the sprite animation to have completed for the door to open: [src/trigger/door.cpp:99](https://github.com/SuperTux/supertux/blob/10fe530230b3f2c0067b14a529720c4322cf88f7/src/trigger/door.cpp#L99).

I have not tested this, but it's a theory.

**Comment by MatusGuy** [comment]
... a game theory.

This is a problem with the door and not that commit. Do you want to tackle this?

**Comment by Vankata453** [comment]
> This is a problem with the door and not that commit. Do you want to tackle this?

Actually, I have seen such sprite `animation_done()` logic used many times in the code. I think this bug may exist for other objects too. I don't think it's the door to blame for this one, but rather either the way `Sprite` updates, or the concept of not drawing off-screen objects.
