### ISSUE TITLE
Bad savegame location on Windows

### ISSUE THREAD

**Issue by Grumbel** [SuperTux/supertux#289]
The game dumps its save and configuration files straight into `C:\Users\user\supertux2\`, that is not the proper way to do it. I am not sure if Windows has a proper location for savegames and stuff, as every game does it differently, but `C:\Users\user\Documents\supertux2\` seems to be frequently used.

SDL2 also has a function for that: https://wiki.libsdl.org/SDL_GetPrefPath

Downside is that that function does lead to ugly `{Company}/{SoftwareName}/`  style path names which I never liked.

On Linux we also lack XDG support, so ~/.supertux2/ should really be ~/.config/supertux2/ and maybe some ~/.local/share/SuperTux2/ (spec is really unclear and what is supposed to go there, so sticking with just ~/.config/ should be fine).

**Comment by Mathnerd314** [comment]
This is the loading code: https://github.com/SuperTux/supertux/blob/master/src/supertux/main.cpp#L146
Looking at PhysFS, it seems we should be using ``PHYSFS_getPrefDir`` instead of `` PHYSFS_getUserDir``: https://icculus.org/physfs/docs-devel/html/physfs_8h.html#acd87392d234d070695303521bb8052a5. It has similar API to SDL's.

**Comment by maths22** [comment]
See 31ca9758c2b5c51ab4e185bfad163c63eecef4a9 (SDL_GetPrefPath was preferred over PHYSFS_getPrefDir for consistency with issue #290) Suggestions/improvements welcome.

**Comment by Mathnerd314** [comment]
That uses XDG_DATA_HOME/Supertux/supertux2 on Linux too (https://hg.libsdl.org/SDL/file/tip/src/filesystem/unix/SDL_sysfilesystem.c).  A uniformly ugly path, but there's already been 2 arguments on that code, so I guess it's a de-facto standard,

We could use XDG_CONFIG_HOME for the config file, but I don't think that would interact well with addons. According to https://bugzilla.gnome.org/show_bug.cgi?id=300940, any doubt should be resolved in favor of the data dir. Thus, closing this since it's done.

**Comment by maths22** [comment]
Fixed in 16276f2f3f342b24e7e3608de1c7ffdfeeabf1dc
