### ISSUE TITLE
Freeze after changing volume/opening activities in fullscreen OpenGL mode

### ISSUE THREAD

**Issue by flipflop97** [SuperTux/supertux#304]
On Gnome 3.18.2, Arch linux, if you start the game using OpenGL and change the volume in game, the game crashes and must be force-closed.

**Comment by maxteufel** [comment]
Can't reproduce that using Arch Linux, also Gnome 3.18.2. Are you using something for audio that doesn't involve PulseAudio?

**Comment by flipflop97** [comment]
Nope only using pulseaudio, but I just found out it only happens in fullscreen, and entering the activities screen also triggers the freeze. So it must be something else.

**Comment by maxteufel** [comment]
As we weren't able to reproduce this issue and haven't heard about more details from @flipflop97, close this.

**Comment by BlaCoiso** [comment]
I can reproduce this on Windows: if I'm playing fullscreen and I press the Windows key, this happens. Then I have to press Alt+F4 and open the game again.

**Comment by maxteufel** [comment]
This is most likely some problem with incorrectly handling this in SDL.

**Comment by maxteufel** [comment]
@tobbi suggested SDL 2.0.4 might fix this issue. @maths22 can you build a Windows version using SDL 2.0.4 and try to reproduce this?

**Comment by maxteufel** [comment]
Some searches in SDL's commit log and bugtracker support the theory that this is a problem in SDL (possibly <https://bugzilla.libsdl.org/show_bug.cgi?id=2922>). It looks like freezes are a rather common problem for them. If you still experience this problem with SDL 2.0.4 linked to SuperTux, please report the problem to the SDL developers. If they say this is actually a SuperTux problem, reopen the issue. Otherwise ask them to fix it and wait for them to publish a fixed version. Until then, all you can do to avoid this is avoiding the described situation that leads to the problem. If this turns out to be a problem in SuperTux, we will investigate as soon as possible but as already said, we do not believe this is a problem in SuperTux.
