### ISSUE TITLE
Carried objects can be released through solid magic blocks

### ISSUE THREAD

**Issue by IndianaTux** [SuperTux/supertux#335]
Version 0.4.0   Windows 7 64bit
Throw any lantern at a solid magic block stack and the lantern will go through it. Make sure Tux throws the lantern half a tile close to the magic block stack. I noticed this glitch in previous SuperTux versions.

.

**Comment by Hume2** [comment]
The magic blocks have a short switch delay, so when the lantern falls quick enough, it can fall trough the magic blocks before they start to be solid. This is intended feature I think.
There are two ways you can deal with that. You can make the ambient light brighter so it will trigger much earlier or you can put darker magic blocks, because they don't need so much light to switch on.

**Comment by maxteufel** [comment]
> This is intended feature I think.

I agree that this can be seen as an intended feature. As such, this issue is invalid and will not be fixed.

@SuperTux/core, @SuperTux/developers: Please reopen this if you have serious concerns about this being the way it is.

**Comment by LMH0013** [comment]
I think you guys have misunderstood what the bug is.  This occurs when the magic blocks are already solid, so the time delay before the block switches is irrelevant: the block is static.  Furthermore, the intended purpose of the switch delay is to prevent the blocks from flickering rapidly if the light threshold should oscillate quickly, not to allow lanterns to pass through first (such a "feature" doesn't really make any sense anyway).  I don't even think that lanterns can be dropped through magic blocks before they turn solid anymore anyway, the time delay was reduced to prevent that.

I have confirmed that the bug exists, and that it is not isolated to lanterns.  Indeed any object Tux can pick up can be passed through a solid wall of magic blocks (including badguys).  Thickening the walls causes funky behavior too.  The object progressively passes through a depth of two blocks, anything thicker and the object migrates downward.  There is definitely a glitch here.

**Comment by Karkus476** [comment]
Here's a level to test the bug:
[issue335.stl.txt](https://github.com/SuperTux/supertux/files/111040/issue335.stl.txt)
and a recording of how to test it.
[issue335_recording.txt](https://github.com/SuperTux/supertux/files/111039/issue335_recording.txt)
Please tell me if I misunderstood what this bug is...
Interestingly, this makes me notice a whole other problem. Using the editor, edit the level, replace the light block objects with blocks in the tilemap, or rocks, what do you notice...?
