### ISSUE TITLE
Make sprites go to default when the sprite file is not found

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#384]
Sometimes, editors can add in a sprite section and make it blank. This can result in the icon being a strange blue and red pattern.

**Comment by Hume2** [comment]
This is really an issue, but further please report it to the editor in that the issue appears.
* https://github.com/SuperTux/supertux-editor for the mono C# editor
* https://github.com/SuperTux/flexlay for the flexlay editor

I guess, this is the mono C# editor issue.
I'll let this isue open since we don't have a stable editor so far and many people still use the mono C# editor.

**Comment by brmbrmcar** [comment]
I am using the mono one. I could see if it occurs in Flexlay. However, I'm not sure it is all the fault of the editor. It should never happen anyway.

**Comment by brmbrmcar** [comment]
Does e4b1e94 fix the problem?

**Comment by Hume2** [comment]
I don't think so. This works only for cases where the sprite isn't defined at all.

**Comment by Hume2** [comment]
I've just fixed that. Please test whether it works for all objects.

**Comment by brmbrmcar** [comment]
I'm unable to test it at this point.

**Comment by Hume2** [comment]
I've tested it myself on bonus blocks. Is this your case?

**Comment by brmbrmcar** [comment]
I have come across the issue with bonus blocks before.

**Comment by Hume2** [comment]
OK, I'll look whether there isn't any issue in other objects.

**Comment by brmbrmcar** [comment]
And also, you can still set sprites that are not default now, right?

**Comment by Hume2** [comment]
Yes, it's still possible.

**Comment by brmbrmcar** [comment]
OK, I just wanted to be sure.

**Comment by Hume2** [comment]
So now it should work for all objects.
