### ISSUE TITLE
Freezing a primed haywire bomb with ice flower causes game to crash

### ISSUE THREAD

**Issue by Yoshi678** [SuperTux/supertux#391]
**SuperTux version: 0.4.0**
**System information: Windows 10 home Version 1511, 64-bit system, Intel core i5-4210 UCPU @1.70GHz 2.40GHz** 

##### Additional debugging information: Uhhhh....

I know bugger all about coredumps etc. The level I found this in was "Entrance to Toad Castle" within the Mattie's Iceberg world, I've tried it in other levels, both custom and not, with the same result.

**Comment by tobbi** [comment]
xref #334 
Unfortunately, our download server is down, but #334 suggests that it is fixed in a recent nightly build.

**Comment by tobbi** [comment]
I got this in wine: [FATAL] C:\projects\supertux-9ml4d\src\supertux\main.cpp:444 Unexpected exception: Couldn't unqueue audio buffer: Invalid Value

**Comment by tobbi** [comment]
It crashes here: https://github.com/SuperTux/supertux/blob/ca101a9d356894276b6c7479325f42ba5c162e8e/src/audio/stream_sound_source.cpp#L66

**Comment by tobbi** [comment]
So, the fix is taken from http://trac.wildfiregames.com/ticket/297 which caused the same issue to happen, and I do hope this is the same cause. 

Unfortunately, I cannot test at the moment, because I don't have a build system for Windows set up. If you can, please compile SuperTux yourself or wait for a Windows nightly build to appear (could take a while, afaik the server is moving to a new location).

If you want compile instructions, go here:
https://github.com/SuperTux/supertux/blob/master/INSTALL.md

**Comment by tobbi** [comment]
I just tested it myself in Wine and the fix appears to be working. If you guys want to test it yourself, go ahead and use a nightly build from http://download.supertuxproject.org/download/
