### ISSUE TITLE
Distribute on Itch.io

### ISSUE THREAD

**Issue by nclm** [SuperTux/supertux#415]
[Itch.io](https://itch.io) is a platform for discovering and distributing games. The community there is very welcoming to newcomers, and it’s very easy to set up a page to offer the game to download for free (it’s also possible to allow optional donations, if ever the _SuperTux_ project need some).

With the right tags and categories added to the game, I think it can be a good place to have more people discovering _SuperTux_.

**Comment by maxteufel** [comment]
Thanks for your suggestion.

I like this idea and it seems to be way easier to make use of that platform than getting the game on Steam (where we'd even need to pay).

> (it’s also possible to allow optional donations, if ever the SuperTux project need some)

We've already considered this idea, however right now the problem is that no one wants to take the legal responsability for donations (making sure we don't violate tax laws etc.) nor do we have the money to get legal advice.

**Comment by Karkus476** [comment]
Ping pong that this might be an option now that donations are set up.

**Comment by maxteufel** [comment]
Indeed. However, we still need some way to provide generic Linux builds, see SuperTux/supertux#648. Unless we temporarily only provide macOS and Windows builds there and put on a note about Linux builds.

**Comment by wrldwzrd89** [comment]
With AppImages available, solving the Linux problem holding this up, perhaps it can finally move forward? Do keep in mind that the itch app v25 makes changes to the acceptable app distribution methods. This shouldn't affect going forward with itch, though, as SuperTux doesn't use anything on the block list.

**Comment by tobbi** [comment]
@maxteufel Shall we give this a shot? Now or when we release 0.6.0 ?

**Comment by tobbi** [comment]
I just distributed it on itch.io: https://supertux.itch.io/supertux
