### ISSUE TITLE
Real time can go faster than game time

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#416]
This is a bad issue, especially for things like full-game runs. https://www.youtube.com/watch?v=Ckbl5XTfxuA&t=6m19s demonstrates the issue.

Edit by Hume2: The video of the gameplay is 6:16 long, but the score shows 6:30.

**Comment by Hume2** [comment]
It's because we don't want the lags to affect the score, so you don't need a super-computer to reach the best time.

**Comment by brmbrmcar** [comment]
Only the very fastest computers can reach the speed. I see the intention, but the game needs a better limit. So don't just shut down my issues because you don't like them and you wish to overuse power.

**Comment by brmbrmcar** [comment]
This is not invalid. Remove the tags and reopen. The game should NOT go too fast. It is not an issue with game time. The game timer just goes, as expected, the time of the game.

**Comment by maths22** [comment]
I'm sorry, but I think Hume2 was misinterpreting the issue.  He is correct that allowing the game time to go slower than real time is desired (i.e. a video where the time said 7:00, but the game said 6:30 would be OK, since that meant game time was slowed down for performance reasons).  However, this is an issue where game time is faster than real time, which should not happen.

**Comment by brmbrmcar** [comment]
That is the issue.

**Comment by HybridDog** [comment]
Does this still happen?
https://github.com/SuperTux/supertux/commits/master/src/supertux/screen_manager.cpp

**Comment by tobbi** [comment]
I recorded myself playing a level and compared the time of the recording with the time displayed in SuperTux. They were almost identical. I'm gonna close this issue.
