### ISSUE TITLE
Releasing a trampoline into portable rocks causes Tux to end up in ground

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#535]
Originally found by @brmbrmcar. 

See the video of the bug here: https://www.youtube.com/watch?v=DGqPW-u_Ylk&t=0s

We should find out what the hell is wrong with this. As you can see, when releasing a trampoline into portable rocks, Tux somehow ends up in the ground. 

Let's figure out what's wrong.

**Comment by maxteufel** [comment]
This is because when you attempt to release the trampoline into the blocks, it tries to push away the blocks because there is no other space for the trampoline. However then there is no space for the player anymore and they get pushed into the ground. This also happens with other portable objects. I do not consider this a bug.

**Comment by Karkus476** [comment]
@maxteufel This is definitely a bug, as Tux shouldn't be pushed into the ground, in the situation which arises he should be killed, rather than pushed into the ground. But this situation shouldn't arise as Tux's hitbox should increase in size when holding an object and therefore he should not be able to release it within the other objects.

**Comment by Karkus476** [comment]
This only works with a stack of rocks, and is connected in some ways to this: #395
and in others to this: #469

**Comment by maxteufel** [comment]
Portable objects (more specifically rocks, trampolines) shouldn't be reordered in a strange way as well.

**Comment by Ordoviz** [comment]
It looks these are two bugs: the unfortunate objects physics and the ground thing. Here is a video showing another way to end up in the ground like this: https://www.speedrun.com/st/guide/afj1z

**Comment by weluvgoatz** [comment]
Does this still happen?

**Comment by weluvgoatz** [comment]
Due to the lack of activity on this issue, but mostly my complete inability to reproduce it, I'm going to close it for right now.  If the issue comes back feel free to re-open.
