### ISSUE TITLE
Jump not working while running

### ISSUE THREAD

**Issue by kristho91** [SuperTux/supertux#549]
SuperTux version: v0.5.0-rc.1-8-g635693a
System information: Solus 1.2, kernel 4.7.0. SuperTux installed from distro's repository

##### Expected behavior
Be able to jump when walking (pressing right, and press space to jump).

##### Actual behavior
It seems to ignore my jump, so I just run directly into death ;)

##### Steps to reproduce actual behavior
Hold right-arrow down to run and then press space to jump - does not always do the expected.

**Comment by maxteufel** [comment]
`v0.5.0-rc.1-8-g635693a` is outdated, please try with latest master. Additionally I do not see any commit g635693a in our repo so this is probably an unsupported third-party patch. Solus does not seem to provide any more recent SuperTux than <https://git.solus-project.com/packages/supertux/> so I'm not sure if the information provided is valid.

I'm almost sure that such a core function of the game is not broken. I have played the game multiple times before and since the first RC.

> Hold right-arrow down to run and then press space to jump - does not always do the expected.

'Not always' implies it works sometimes. Please describe that better, Also when do you expect it?

Cc: @SuperTux/core 
Cc: @SuperTux/developers 
Please close this if it's 'works for me'.

**Comment by Karkus476** [comment]
@maxteufel What about https://github.com/SuperTux/supertux/commit/635693a ? The "g" might stand for git.

**Comment by maths22** [comment]
The g does stand for git.

Certain keyboards/operating systems do not support certain key
combinations, and there is nothing we can do about that.  Try changing the
key bindings and see if the behavior resolves itself.

**Comment by maxteufel** [comment]
Please reopen if this is still an issue and you can describe it better.
