### ISSUE TITLE
Badguys don't climb some slopes

### ISSUE THREAD

**Issue by BlaCoiso** [SuperTux/supertux#587]
**SuperTux version:** 0.5.0 rc3
**System information:** Ubuntu 16.04 32bit

##### Expected behavior
Badguys would climb all slopes

##### Actual behavior
They don't climb the slope and instead turn back

**Comment by Karkus476** [comment]
Please create or link to an example level which displays the bug.

**Comment by BlaCoiso** [comment]
I made an example level, here's the link: https://gist.github.com/anonymous/9e7716cff70ee2fa2842b315f55ffb58/raw/dda69ee31b8ea8e4dd6f472ebf827ccde94bbd81/bug.stl

**Comment by BlaCoiso** [comment]
On the last slope, the badguy gets stuck and dies

**Comment by maxteufel** [comment]
I think we can agree both parts of the issue are intended behavior.

> Badguys would climb all slopes

Badguys turn around when the collision detection code detects a collision on a side and the badguy hasn't already turned around on that side. In the case of steep slopes, the collision detection code reports a collision on the side, so the badguy simply turns around.

> On the last slope, the badguy gets stuck and dies

That is because it is too wide - it doesn't fit on a one tile area. You can try that with any single-tiled thing, and put a walking badguy on it that doesn't fall from platforms. It will die.
