### ISSUE TITLE
Building 0.1.3

### ISSUE THREAD

**Issue by FSMaxB** [SuperTux/supertux#601]
Just for reference: The two modifications that are required for building SuperTux 0.1.3:

* Set the C++ standard to C++03 (necessary for GCC6): 
`$ CXXFLAGS="-std=c++03" ./configure`
* Remove `Menu::` from `src/menu.h`: `sed -i -e 's/Menu:://g' src/menu.h`

See [Bug Report](http://supertux.lethargik.org/bugs/view.php?id=396) and [Mailing List](http://lists.lethargik.org/pipermail/supertux-devel-lethargik.org/2010-March/006719.html)

**Comment by maxteufel** [comment]
SuperTux 0.1.3 is not supported anymore. Please don't report any bugs for it. Furthermore you are advised not to build it. It might contain serious (security) issues.

If you encounter any issues with the more recent versions of SuperTux (v0.4.0+), please report them so we can see if it can be fixed, rather than going back to an outdated old version of the game.
