### ISSUE TITLE
SuperTux installer not creating an Desktop shortcut

### ISSUE THREAD

**Issue by bigdaddy999** [SuperTux/supertux#748]
**SuperTux version: 0.5.1**
**System information:** *Windows 10 Home Single Language 64 bits*

##### Expected behavior
Desktop icon

##### Actual behavior
not creating an Desktop icon

##### Steps to reproduce actual behavior
None

##### Additional debugging information
None

i have an Windows 10 system and it won't create an desktop icon after completing installation
what i do

**Comment by tobbi** [comment]
If we're using CMAKE_CPACK, I think we need https://cmake.org/cmake/help/v3.7/module/CPack.html#variable:CPACK_CREATE_DESKTOP_LINKS

**Comment by maxteufel** [comment]
Is that optional (as in, selectable by the user)? Because I personally think those desktop shortcuts are more of an annoyance than helpful.

I don't know how this is handled by the current installer. If it asks the user but doesn't create, then yes @tobbi, we need to add that. If it doesn't right now and also won't do that when given said information I'd be against it. If it does ask the user, then great.

**Comment by maths22** [comment]
Cpack CPACK_CREATE_DESKTOP_LINKS doesn't seem to leave a checkbox, and I'm in agreement that installers that litter undesired shortcuts are worse than ones that don't create them, since you can always make a desktop shortcut by drag-and-dropping the start menu entry.
