### ISSUE TITLE
Badguys turn away from slopes >22.5°

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#761]
**SuperTux version:** Latest revision

##### Expected behavior
Badguys walk up steeper slopes.

##### Actual behavior
Badguys turn away from steeper slopes, as if they were a ledge (including badguys that usually fall off ledges, e.g. snowballs)
Breaks a bunch of designs to make badguys from a dispenser come upwards out of pipes, e.g. in level 2 of the addon 'Mattie's World'. Instead they get caught between the slope and dispenser and die.

##### Steps to reproduce actual behavior
Can be seen in any level with badguys and slopes.

**Comment by brmbrmcar** [comment]
It makes some badguys almost impossible to kill or not die to, but they would basically end up going vertically upwards without a limit. I imagine the behaviour is intentional.

**Comment by 165your4** [comment]
To be clear, this hasn't always been the case, and I believe it's a fairly recent bug(?) or intended change.

**Comment by maxteufel** [comment]
How recent? If recent like in the last year or so, this is most likely a bug.

**Comment by 165your4** [comment]
Hmm, I'll check the past few versions and see if it's present there.

**Comment by maxteufel** [comment]
@165your4 if you use a git clone, you can use a tool called `git bisect`, that allows doing this in a way that saves you time.

You start the tool with `git bisect start`.

If you start this on the master branch, you mark the current master, where the issue is obviously present, as bad by doing `git bisect bad`.

You then go a very long time, e.g to the 0.5.0 commit (`git checkout <commit hash>`), where the issue is *not* present and you mark it as `git bisect good`.

Now it will automatically start a tool. It will jump half-way between the commits. If you have 10 commits in between good and bad, it will jump to the 5th commit. You test the 5th commit. If it's bad, the issue was introduced in the commits before, if it's good, the issue was introduced later. You mark the status of the commit it is currently testing with `git bisect bad` (issue there) or `git bisect good` (issue not there).

It will continue to narrow it down like this, which will save you a lot of time, compared to testing all the 10 commits.

Imagine doing this with 1000 commits. After the first try, your search will be reduced to 500 commits. (But you continue with that method).

If it finds the first bad commit, it will tell you (see #777 for how the message looks like).

**Comment by maxteufel** [comment]
Oh and obviously when you use a git clone and do this: you will always need to recompile and check if the issue is there. If you don't recompile, you won't use the commit it's currently at, so that breaks the whole thing.

**Comment by busybody42** [comment]
They should not walk up 90° slopes or higher, but walk up lower slopes tux can walk oh!

**Comment by busybody42** [comment]
I mean walk on

**Comment by HybridDog** [comment]
The problem still happens:
https://user-images.githubusercontent.com/3192173/109308798-cb5d5c00-7842-11eb-8c0d-a64b0e7bbe24.mp4
