### ISSUE TITLE
Milestone 2.5: autumn forest add on!

### ISSUE THREAD

**Issue by busybody42** [SuperTux/supertux#795]
Images from Irc chat do not work for now
12 levels (and 1 bonus)
Autumn themed enemies and new sprites!
New tiles!
Sasquatch mini Boss!
Better ghost tree! 
Totems!
And flying pumpkin/Kirby!

**Comment by maxteufel** [comment]
1. What are you trying to tell us with that issue? Please make it self-contained, i.e. don't refer to IRC and explain everything from there here (especially that this is your idea). That will help anyone who sees this issue.
2. There are no milestones anymore. We have releases (v0.4.0, v0.5.0, v0.5.1, …).
3. I don't know if you realize this. But creating something like this is not an easy process, as new code will have to be written, new graphics will need to be created, and this needs a story. This requires a lot of work, which we don't have now, since we're working on actually improving the Forest Island (from a state of being a mess of test levels to a state of having a story, …).
4. Creating a proper story will be hard for this, as the previous story is not fixed anyway. So either it needs an independent story, or the story might not make sense in the future.
5. Lastly, if *you* want to work on this anyway, then feel free to do so. That would include having a certain plan for your add-on, then creating code, graphics, and levels.

**Comment by busybody42** [comment]
for 1. This is to wait for the forest world's official release, and for fun. 2. The milestone 2.5-ish part was just to tell it will be similar in a way. 3. Many new sprites, and some code changes for some new enemies. and the tilesets? hah! that's the power of the paint tool! 4. It's not even for the main story! it's an add-on! It doesn't NEED a story (but i will make one if you want!) just like the bonus islands! 5. I make graphics, then code, then levels. (and some sprites are already in the files, like wooden jumpy!)

**Comment by maxteufel** [comment]
I'm looking forward to see first previews of your add-on!

**Comment by busybody42** [comment]
They will use a custom background, made with 4 layers!
