### ISSUE TITLE
The game is dead and very much a waste of time

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#836]
https://forum.freegamedev.net/viewtopic.php?f=68&t=7925
Read this, please. I hope you see where I'm coming from.

**Comment by qwertychouskie** [comment]
Although I agree ST does not have many "unique" elements, here's where I disagree: It's still a fun game.  A game does not have to be original to be fun.  Look at e.g. [OpenRCT2](https://github.com/OpenRCT2/OpenRCT2): it is not just a clone, but a reverse-engineering and re-implementation of RCT2.  That's what makes it what it is.  Don't get me wrong, I like original elements (e.g. SuperTuxKart's nitro) but you don't necessarily have to be original to be fun.

**Comment by Hume2** [comment]
Hello, it's a long time you haven't heard of me and excuse me that I vanished without letting you know but it seems you were doing well. Currently I am more focused on other projects, but I'd like to share my opinion.

I always liked SuperTux, I don't mind that it's just other game's clone, but the other points are important. I agree that there are many features those were added for absolutely no reason. Maybe there was a reason but it was forgotten or went invalid because of new plans.

Another point is that the ambitions were always far bigger that the real power of making them real. And also I don't remember that there has ever been a complete detailed plan of planned features which went into that the ambitions were growing with each update. This caused that the game never seemed as complete and many senseless features were introduced.

I think that the game _could_ be reviewed again but it would mean a bigger overhaul. Firstly, all features those don't look well or are redundant should be deleted. There are a few groups of features those look similar, are used for the same concept but are still different. For these cases, only one of each group should be kept and the rest should be dropped. There are also features those were used just a few times or maybe even not at all. I'd recommend you to delete them as well. Secondly, make a complete and detailed list of features those should SuperTux contain. Think a lot about each feature whether it should be there or not. After you decide, do not change the plan unless really have to. If you think a new super feature that SuperTux could contain, don't add it there, put it to a separate list instead. After you have a plan, implement only the features in the plan. Add extra features only if it's going to be implemented together with a feature included in the plan. Thirdly, remember that there are always things those could be improved any time. In my opinion, it would be good to complete the planned features in half-quality and then improve. And remember, SuperTux could be smaller than it's now but it should be complete. SuperTux in its current state doesn't seem as complete (or has anything changed after I vanished?).

Another option that comes to my mind is that SuperTux in its current state could be made complete. I'd advice you not to add any new features, fix only the most important bugs and make the game seem complete just with the current resources and just the fewest additions as possible. After that, the unused features could be given a usage. I'd likely focus on giving the current useless resources a usage instead of making brand new features. A detailed list of planned features might be also handy. It might be hard to give some things a usage, but it would be still compatible with old levels.

If you decide to make another game, I recommend you to make a list of features too. And don't let your ambitions to grow too fast.

Just if you are curious, I migrated to GitLab, because it's not owned by …

**Comment by Alzter** [comment]
I see what you mean. Although, if we were to complete the game using only what we had, using unused features as mechanics would be a **bad idea**. Most unused badguys are unused for a reason. They're unfair, and very broken. This is why I don't like levels that spam those badguys such as the owl. I'd reccomend reading this. It's a very helpful article on good techniques to employ when trying to finish a game. [http://makegames.tumblr.com/post/1136623767/finishing-a-game](http://makegames.tumblr.com/post/1136623767/finishing-a-game)

**Comment by weluvgoatz** [comment]
I kinda disagree with Alzter's point about how the game is "dead" (just
stop playing it then) but this article did seem to be useful.

**Comment by Alzter** [comment]
Re @Hume2's post: It seems the latter approach is being taken with the current direction of the game being to conclude Story Mode through adding the final worlds: Tropical Paradise, a volcanic subsection of Tropical Paradise, and Nolok's final fortress.

I still feel a lot of things could be polished over but I'm not sure how I can help, I definitely feel making a new SuperTux Wiki page could help co-ordinate contributions more easily.

**Comment by papb** [comment]
Hello, just wanted to say that I really like this game, since my childhood, and it is definitely not a waste of time. Thanks to all contributors who helped this game to exist!

**Comment by Laksh61** [comment]
@Laksh61
