### ISSUE TITLE
Multiplayer: Save player controls for multiple players in settings file

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#852]
Currently, only the player controls for one player are saved in the ```keymap``` property in the settings file. If we want to support multiple players, we need to save player controls for both players in the settings.

**If we do this, we still need a backwards compatible way of reading the previous keymap settings, so that those don't get lost.** 

This will need a bit of discussion, I guess. So I'm gonna mark it as such.

**Comment by bou6** [comment]
I started to work on this issue and actually I succeed to give different keyboard config and the 2 players are moving separably. the way I have done this is that in the KeyboardConfig::keymap, I added one other attribute id of the player to the map so that the map looks like (SDL_Keycode, Control, playerId), and also gave an Id to each player. The Idea is that in KeyboardManager::process_key_event looks at which player belongs this SDL_Keycode (using the map) and then updates it's controller.

The good thing is that we don`t have to change to much in the architecture. but I didn't like the fact of using a 3 element map.

What do you think about duplicating the InputManager instead of using a singleton ?

**Comment by tobbi** [comment]
Hey @bou6 can you check in your code somewhere we can take a look? I actually would give you as much freedom as you'd like when it comes to how you achieve this.
