### ISSUE TITLE
Split up 4x4 tiles into multiple tiles

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#895]
4x4 tiles are hard to handle especially for the editor and our rendering engine etc.

We should split them into 1x1 tiles.

**Comment by weluvgoatz** [comment]
I agree, and if this happens, maybe some decals could be made into splitup tiles? Just an idea.

**Comment by Grumbel** [comment]
Done in 8ef519f86 for the cave background tiles. Only levels I could find that use the old cave tiles are, these need manual fixing:

* `community2016/levels/community2016/Uncontrolled_Lift (gelada).stl`
* `niso-yetis-revenge/levels/yetis_revenge/Blue Mountain.stl`

exitfg/bg tiles are auto-converted to decal since 01ed5a7f60c07f78ab8590ea3be39a97a3f69bfb, however the z-pos of them is still wrong.

Haven't bothered with `tiles/doodads/havoktux-0.png` as that only seems to be used by `data/levels/test_old/easteregg.stl`, market that one as deprecated.

**Comment by weluvgoatz** [comment]
Tbh, when I first used the editor, I thought all the tiles were 1x1, so it was confusing at first.

**Comment by Grumbel** [comment]
Fixed the two levels in 61b288c and e7de705.

Remaining bigger-than-32x32 tiles:

tiles/doodads/nolok-statue.png
images/tiles/doodads/grass2.png
tiles/doodads/platter.png
