### ISSUE TITLE
Tiles are randomly placing themselves????

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#940]
For some reason, in the newest nightly build, tiles start randomly placing themselves in the editor! I cannot seem to find one specific time when they do, but I place a few tiles, switch to some different ones or save the game or something like that, and the game randomly places some tiles where the little penguin face was. This is very annoying and I don't know wheat's going on. Please fix.

**Comment by Grumbel** [comment]
Could you provide a screenshot? Does it happen with all tiles or just with some? In all levels or any specific ones?

**Comment by Rusty-Box** [comment]
From what I can recall, these “random” placed tiles aren’t that random placed at all.
The issue here is that when clicking somewhere on the editor’s menus (like when selecting a different tilemap in the tilemap menu or selecting a tile/object from the tilegroup/object menu) it places a tile or object right behind the space that is covered by the menu (as if instead of selecting something you just placed something in the level while doing so).

I hope this makes sense. Don’t know how to better explain it really.

**Comment by weluvgoatz** [comment]
I think @Rusty-Box's description/explanation is more accurate. It happens regardless of the level/tiles. It even happens with objects.
