### ISSUE TITLE
Add music fade in and out scripts

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#962]
**SuperTux version: 0.6.0 Alpha 3**
**System information:** *Windows 10*

Title says it all. This could be used in levels like the castle of Nolok where the music could fade out at the end instead of abruptly stopping.

**Comment by Alasdairbugs** [comment]
Yeah this would also be useful for custom stages, maybe an option to choose the time period at which the music fades out over?

**Comment by weluvgoatz** [comment]
I'm pretty sure this has already been implemented.

**Comment by tobbi** [comment]
This requires adding a fade in / fade out method to scripting/sector.cpp / .hpp.

Then you'd have to add the appropriate methods to the MusicObject class and then have that call appropriate SoundManager classes.

I'll be the mentor for this one.

**Comment by oribro** [comment]
@tobbi Hi, I'm new here and trying to solve this issue. Can you give some advice?
Thanks

**Comment by tobbi** [comment]
Hello @oribro ,

SuperTux uses Squirrel for scripting (but you don't need to know it in order to help with this issue). First and foremost, all the methods that are available to scripts are in the `src/scripting` directory. There you can see the different object classes, which have scripting methods themselves, which can be called from scripts.

Each sector has a MusicObject instance for the music that is played. See here for the available methods: https://github.com/SuperTux/supertux/blob/6627ddd58e60aab0781022837904eadd091e286c/src/object/music_object.cpp

You can see here how to reference the MusicObject from a sector instance:
https://github.com/SuperTux/supertux/blob/f31276d3d6a4d4ce2d593d750190197e3bb2a4e3/src/supertux/game_session.cpp#L143

The method in question that you need to add to the MusicObject would be `stop_music(float fadetime)`, `pause_music(float fadetime)` and `resume_music(float fadetime)`.

If you need more info, we're available here: https://matrix.to/#/!BfYVBjzEVacHrvDBYw:matrix.org?via=matrix.org&via=synapse.vpzom.click and hopefully someone will get back to you.

**Comment by VictorJL** [comment]
I can work on this one. Just brewing my coffee, shall be ready in no-time.

**Comment by Rusty-Box** [comment]
Apparently this issue was not closed after the #1370 0 was merged so ... I'm closing manually.
