### ISSUE TITLE
ice flames get displaced 3 blocks to the right

### ISSUE THREAD

**Issue by Alasdairbugs** [SuperTux/supertux#968]
v0.6.0 beta-1
win10 64bit

##### 1: boot up v0.5.1
2: make a level, marking where you placed the ice flame (this may also work for the regular flames?)
3: save the level, boot up v0.6.0 beta-1 and import it into the add-ons/test folder
4: go into the level editor, into the stage and the ice flame should be in a different position.

**Comment by Semphriss** [comment]
I think this was a known issue, at some point it was mentionned that flames were displaced and had to be repositionned.

I'm closing since it was left unanswered for over two years, if there is still a need to do something about it please open a new issue so it can pop at the top of the issue list :slightly_smiling_face:
