### ISSUE TITLE
Restore Yeti's "throwing bouncing snowball" attack

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#979]
In an older version of SuperTux (I believe it was v0.3.0) the Yeti had a second attack besides stomping. Throwing a few bouncing snowballs when he's on either side of the boss arena. This attack should be restored to make the first boss a bit more challenging. As an additional idea would be that this attack only activates once the yeti has only 2 or 3 lives left making it some sort of "special attack".

**Comment by brmbrmcar** [comment]
It should only be readded as an option IMO, as it would break many other levels using it.

**Comment by Rusty-Box** [comment]
@brmbrmcar Focusing on that might prevent us from actually adding/changing something in general since there will always be a change or addition that can breaks other levels. So in my opinion this is not a totally valid argument to me honestly but I get why it would be for some others.

**Comment by Alasdairbugs** [comment]
No. It should be added as an option because some people may or may not want the additional attack, because it may make a fight impossible (i.e, if someone were to make a hard fight where you could only be in one place at one time, and by some random event, a bouncy snowball were to be there, it would make the level impossible since they couldn't escape it). It would be better adding an option where the player could choose between it sending a bouncy snowball attack, or simply, some other attack, since the style of the fight doesn't have to be a yeti. You could always make a sprite where its not a yeti, let's say a forest-world type boss, therefore spawning bouncy snowballs would not fit the theme of the fight since they are a snowy type of enemy. It's a very bad idea simply just restoring the attack as it used to be. The game has progressed to an extent where more variety is wanted.

**Comment by Rusty-Box** [comment]
I personally see “wanting more variety“ in certain areas not as a bad thing, but it can be pretty much hindering when it comes to things like boss enemies. When developing and designing a new boss (a current case: the ghost tree) its behavior will fit the badguy it was originally made for, (which in this case would be the ghost tree). An example for that would be its basic root-attack. It was made because a tree boss could use its roots to attack from below and was never meant for changing the sprite to something that wouldn‘t benefit form this attack being based on roots of a tree as it is intended for a tree based boss fight. Same would go for the yeti. He was created as a boss for the ice world and even once had a ice world specific attack which was throwing bouncing snowballs. I honestly don’t know the exact reason to why it was removed later on but without it, to me, the yeti just feels like a boring excuse for a boss. Nothing that makes him unique and challenging. Especially in rooms with no yeti related stalactites.
In the end, many of the game‘s elements are subject to change or can get updated if needed and it‘s the responsibility of a level creator to adjust their created levels to work with the latest version. Not necessarily only ours.

**Comment by brmbrmcar** [comment]
Your logic is one way to discourage new level makers and significantly reduce the total number of available playable levels. Adding more customisability doesn't change the boss in its official implementation. You might as well just say we should get rid of all levels that have the yeti or the tree boss that aren't official because they don't fit the desired implementation.

**Comment by Rusty-Box** [comment]
I'll provide the sprites and I assigne @tobbi for the coding part at the moment once the sprites are finished.

**Comment by weluvgoatz** [comment]
Psssst! I've been working on the code portion already! :)! It's not done
though...

**Comment by tobbi** [comment]
Great!

**Comment by Rusty-Box** [comment]
@tobbi Don't worry I will find something for you ;)

**Comment by NickerAban** [comment]
Ah past 2018 for the subject..
